# Copyright (c) 2026 Aerosol d.o.o.
# Licensed under the Aerosol Magee Scientific Software License
# (see LICENSE file for details)

COLUMNS_AE36S = {
    'BCindex': [
        'ID', 'DataID', 'BC880_1H', 'Validity_1H',
        'Babs470_1H', 'Babs950_1H', 'BCff_1H', 'BCbb_1H',
        'BC880_24H', 'Validity_24H', 'BCindex', 'BCff_24H',
        'BCbb_24H',
    ],
    'ClassName': ['ID', 'Name'],
    'Data': [
        'ID', 'TimestampUTC', 'TimestampLocal', 'SetupID',
        'G0_Status', 'G1_Status', 'G2_Status', 'G3_Status',
        'G4_Status', 'G5_Status', 'G6_Status', 'ControllerStatus',
        'DetectorStatus', 'LedStatus', 'ValveStatus', 'PumpStatus',
        'Ref340', 'Sens340_1', 'Sens340_2', 'Ref370',
        'Sens370_1', 'Sens370_2', 'Ref400', 'Sens400_1',
        'Sens400_2', 'Ref470', 'Sens470_1', 'Sens470_2',
        'Ref520', 'Sens520_1', 'Sens520_2', 'Ref590',
        'Sens590_1', 'Sens590_2', 'Ref630', 'Sens630_1',
        'Sens630_2', 'Ref880', 'Sens880_1', 'Sens880_2',
        'Ref950', 'Sens950_1', 'Sens950_2', 'Atn340_1',
        'Atn340_2', 'Atn370_1', 'Atn370_2', 'Atn400_1',
        'Atn400_2', 'Atn470_1', 'Atn470_2', 'Atn520_1',
        'Atn520_2', 'Atn590_1', 'Atn590_2', 'Atn630_1',
        'Atn630_2', 'Atn880_1', 'Atn880_2', 'Atn950_1',
        'Atn950_2', 'BC340_1', 'BC340_2', 'BC340',
        'BC370_1', 'BC370_2', 'BC370', 'BC400_1',
        'BC400_2', 'BC400', 'BC470_1', 'BC470_2',
        'BC470', 'BC520_1', 'BC520_2', 'BC520',
        'BC590_1', 'BC590_2', 'BC590', 'BC630_1',
        'BC630_2', 'BC630', 'BC880_1', 'BC880_2',
        'BC880', 'BC950_1', 'BC950_2', 'BC950',
        'K340', 'K370', 'K400', 'K470',
        'K520', 'K590', 'K630', 'K880',
        'K950', 'BB', 'Babs340', 'Babs370',
        'Babs400', 'Babs470', 'Babs520', 'Babs590',
        'Babs630', 'Babs880', 'Babs950', 'BabsBrC340',
        'BabsBrC370', 'BabsBrC400', 'BabsBrC470', 'BabsBrC520',
        'BabsBrC590', 'BabsBrC630', 'BabsBrC880', 'BabsBrC950',
        'BrC', 'Pressure', 'Temp', 'Flow1',
        'Flow2', 'FlowC', 'PumpDriver', 'PumpSpeed',
        'ControllerTemp', 'InletHumidity', 'InletTemp', 'TapeHumidity',
        'TapeTemp', 'LedTemp', 'LedSourceTemp', 'TapeAdvanceCount',
        'TapeAdvanceLeft', 'CPU',
    ],
    'DataBaseVersion': ['Version'],
    'DateOrder': ['ID', 'Date', 'StartID', 'EndID'],
    'Debug': [
        'ID', 'TimestampUTC', 'TimestampLocal', 'G0_Status',
        'G1_Status', 'G2_Status', 'G3_Status', 'G4_Status',
        'G5_Status', 'G6_Status', 'ControllerFW', 'ControllerSync',
        'ControllerStatus', 'ControllerTemp', 'DetectorVoltage', 'DriverVoltage',
        'LedSourceVoltage', 'DoorPosition', 'FanSpeed', 'TapeAdvanceStatus',
        'ChamberStatus', 'ValveStatus', 'PumpStatus', 'TapeLeftRAW',
        'TapeRightRAW', 'TapePulsesLeft', 'TapePulsesRight', 'FlowCRAW',
        'Flow1RAW', 'FlowRef', 'PumpDriver', 'PumpSpeed',
        'InletHumidity', 'InletTemp', 'DetectorFW', 'DetectorSync',
        'DetectorStatus', 'TapeHumidity', 'TapeTemp', 'ChamberPosition',
        'Ref340', 'Sens340_1', 'Sens340_2', 'Ref370',
        'Sens370_1', 'Sens370_2', 'Ref400', 'Sens400_1',
        'Sens400_2', 'Ref470', 'Sens470_1', 'Sens470_2',
        'Ref520', 'Sens520_1', 'Sens520_2', 'Ref590',
        'Sens590_1', 'Sens590_2', 'Ref630', 'Sens630_1',
        'Sens630_2', 'Ref880', 'Sens880_1', 'Sens880_2',
        'Ref950', 'Sens950_1', 'Sens950_2', 'DetectorStatusCh340',
        'DetectorStatusCh370', 'DetectorStatusCh400', 'DetectorStatusCh470', 'DetectorStatusCh520',
        'DetectorStatusCh590', 'DetectorStatusCh630', 'DetectorStatusCh880', 'DetectorStatusCh950',
        'LedFW', 'LedSync', 'LedStatus', 'LedTemp',
        'LedSourceTemp', 'LedCurrentCh340', 'LedCurrentCh370', 'LedCurrentCh400',
        'LedCurrentCh470', 'LedCurrentCh520', 'LedCurrentCh590', 'LedCurrentCh630',
        'LedCurrentCh880', 'LedCurrentCh950', 'LedStatusCh340', 'LedStatusCh370',
        'LedStatusCh400', 'LedStatusCh470', 'LedStatusCh520', 'LedStatusCh590',
        'LedStatusCh630', 'LedStatusCh880', 'LedStatusCh950', 'Pressure',
        'Temp', 'CPU', 'DiskSpace', 'NumConnections',
    ],
    'ExtDeviceData': ['ID', 'DataID', 'DeviceID', 'DevicePort', 'DeviceData'],
    'ExtDeviceSetup': [
        'ID', 'Timestamp', 'DataID', 'DeviceID1',
        'DeviceID2', 'DeviceID3', 'DeviceID4', 'DeviceID5',
        'DeviceID6',
    ],
    'FilterSet': [
        'ID', 'FilterSetSN', 'Timestamp', 'ch370s1f0',
        'ch370s2f0', 'ch470s1f0', 'ch470s2f0', 'ch520s1f0',
        'ch520s2f0', 'ch590s1f0', 'ch590s2f0', 'ch630s1f0',
        'ch630s2f0', 'ch880s1f0', 'ch880s2f0', 'ch950s1f0',
        'ch950s2f0', 'ch370s1f1', 'ch370s2f1', 'ch470s1f1',
        'ch470s2f1', 'ch520s1f1', 'ch520s2f1', 'ch590s1f1',
        'ch590s2f1', 'ch630s1f1', 'ch630s2f1', 'ch880s1f1',
        'ch880s2f1', 'ch950s1f1', 'ch950s2f1', 'ch370s1f2',
        'ch370s2f2', 'ch470s1f2', 'ch470s2f2', 'ch520s1f2',
        'ch520s2f2', 'ch590s1f2', 'ch590s2f2', 'ch630s1f2',
        'ch630s2f2', 'ch880s1f2', 'ch880s2f2', 'ch950s1f2',
        'ch950s2f2', 'ch370s1f3', 'ch370s2f3', 'ch470s1f3',
        'ch470s2f3', 'ch520s1f3', 'ch520s2f3', 'ch590s1f3',
        'ch590s2f3', 'ch630s1f3', 'ch630s2f3', 'ch880s1f3',
        'ch880s2f3', 'ch950s1f3', 'ch950s2f3',
    ],
    'Log': ['ID', 'Timestamp', 'Severity', 'ClassID', 'MethodID', 'MessageID', 'Message'],
    'Message': ['ID', 'Message'],
    'MessageFlawed': ['ID', 'Timestamp', 'Data'],
    'Method': ['ID', 'Name'],
    'NDtest': [
        'ID', 'FilterSetSN', 'Timestamp', 'Reference',
        'ch370s1f0', 'ch370s2f0', 'ch470s1f0', 'ch470s2f0',
        'ch520s1f0', 'ch520s2f0', 'ch590s1f0', 'ch590s2f0',
        'ch630s1f0', 'ch630s2f0', 'ch880s1f0', 'ch880s2f0',
        'ch950s1f0', 'ch950s2f0', 'ch370s1f1', 'ch370s2f1',
        'ch470s1f1', 'ch470s2f1', 'ch520s1f1', 'ch520s2f1',
        'ch590s1f1', 'ch590s2f1', 'ch630s1f1', 'ch630s2f1',
        'ch880s1f1', 'ch880s2f1', 'ch950s1f1', 'ch950s2f1',
        'ch370s1f2', 'ch370s2f2', 'ch470s1f2', 'ch470s2f2',
        'ch520s1f2', 'ch520s2f2', 'ch590s1f2', 'ch590s2f2',
        'ch630s1f2', 'ch630s2f2', 'ch880s1f2', 'ch880s2f2',
        'ch950s1f2', 'ch950s2f2', 'ch370s1f3', 'ch370s2f3',
        'ch470s1f3', 'ch470s2f3', 'ch520s1f3', 'ch520s2f3',
        'ch590s1f3', 'ch590s2f3', 'ch630s1f3', 'ch630s2f3',
        'ch880s1f3', 'ch880s2f3', 'ch950s1f3', 'ch950s2f3',
    ],
    'ParsedData': [
        'ID', 'DataID', 'Ames_TRP159_Temp', 'Ames_TRP159_Humidity',
        'Ames_TRP159_Pressure', 'AID_TempIn', 'AID_HumidityIn', 'AID_DewPointIn',
        'AID_TempOut', 'AID_HumidityOut', 'AID_DewPointOut', 'AID_DryingPressure',
        'Gill_GMX300_Temp', 'Gill_GMX300_Humidity', 'Gill_GMX300_Pressure', 'Gill_GMX300_DewPoint',
        'Gill_GMX300_Status', 'Gill_GMX500_Temp', 'Gill_GMX500_Humidity', 'Gill_GMX500_Pressure',
        'Gill_GMX500_DewPoint', 'Gill_GMX500_Speed', 'Gill_GMX500_WindDir', 'Gill_GMX500_CorrectedWindDir',
        'Gill_GMX500_Status',
    ],
    'Setup': [
        'ID', 'SerialNumber', 'Timestamp', 'FirmwareVer',
        'SoftwareVer', 'NetworkEnabled', 'Timebase', 'MAC340',
        'MAC370', 'MAC400', 'MAC470', 'MAC520',
        'MAC590', 'MAC630', 'MAC880', 'MAC950',
        'C', 'Area', 'Zeta', 'ZetaCompensation',
        'Aff', 'Abb', 'Abc', 'MacBrC',
        'Pressure', 'Temp', 'ATNf1', 'ATNf2',
        'Kmax', 'Kmin', 'Flow', 'FlowRepStd',
        'FlowCa0', 'FlowCa1', 'FlowCa2', 'Flow1a0',
        'Flow1a1', 'Flow1a2', 'TAtype', 'TAatnMax',
        'TAinterval', 'TAtime', 'TapeRighta0', 'TapeRighta1',
        'TapeRighta2', 'TapeRighta3', 'TapeLefta0', 'TapeLefta1',
        'TapeLefta2', 'TapeLefta3', 'WarmUpInterval', 'AutoTestEnabled',
        'AutoTestType', 'AutoTestDay', 'AutoTestTime', 'MeasureTimeStamp',
        'HomeInfo', 'Display', 'DST', 'TimeZone',
        'TapeAdvanceAdjust', 'ExternalID', 'BHparamID', 'TimeSync',
        'DHCP', 'InstrumentIP', 'SubnetMask', 'Gateway',
        'dRH_Inlet', 'dRH_Tape', 'RH_Error', 'RH_Warning',
        'Average', 'AeroBaudRate', 'AeroDelimiter', 'AdpEnabled',
        'RasEnabled', 'UidepEnabled', 'Language', 'IndexBClimit0',
        'IndexBClimit1', 'IndexBClimit2', 'IndexBClimit3', 'HomeChartPeriod',
        'SystemVersion', 'NTPserver', 'HighConcAlertLimit', 'DNS',
        'ModbusEnabled',
    ],
    'TestReports': ['ID', 'Type', 'Timestamp', 'Passed', 'Report'],
    'sqlite_sequence': ['name', 'seq'],
    'DataView': [
        'ID', 'TimestampUTC', 'StartTimeUTC', 'EndTimeUTC',
        'StartTimeLocal', 'EndTimeLocal', 'SetupID', 'SetupTimestamp',
        'G0_Status', 'G1_Status', 'G2_Status', 'G3_Status',
        'G4_Status', 'G5_Status', 'G6_Status', 'ControllerStatus',
        'DetectorStatus', 'LedStatus', 'ValveStatus', 'PumpStatus',
        'Ref340', 'Sens340_1', 'Sens340_2', 'Ref370',
        'Sens370_1', 'Sens370_2', 'Ref400', 'Sens400_1',
        'Sens400_2', 'Ref470', 'Sens470_1', 'Sens470_2',
        'Ref520', 'Sens520_1', 'Sens520_2', 'Ref590',
        'Sens590_1', 'Sens590_2', 'Ref630', 'Sens630_1',
        'Sens630_2', 'Ref880', 'Sens880_1', 'Sens880_2',
        'Ref950', 'Sens950_1', 'Sens950_2', 'Atn340_1',
        'Atn340_2', 'Atn370_1', 'Atn370_2', 'Atn400_1',
        'Atn400_2', 'Atn470_1', 'Atn470_2', 'Atn520_1',
        'Atn520_2', 'Atn590_1', 'Atn590_2', 'Atn630_1',
        'Atn630_2', 'Atn880_1', 'Atn880_2', 'Atn950_1',
        'Atn950_2', 'BC340_1', 'BC340_2', 'BC340',
        'BC370_1', 'BC370_2', 'BC370', 'BC400_1',
        'BC400_2', 'BC400', 'BC470_1', 'BC470_2',
        'BC470', 'BC520_1', 'BC520_2', 'BC520',
        'BC590_1', 'BC590_2', 'BC590', 'BC630_1',
        'BC630_2', 'BC630', 'BC880_1', 'BC880_2',
        'BC880', 'BC950_1', 'BC950_2', 'BC950',
        'K340', 'K370', 'K400', 'K470',
        'K520', 'K590', 'K630', 'K880',
        'K950', 'BB', 'Babs340', 'Babs370',
        'Babs400', 'Babs470', 'Babs520', 'Babs590',
        'Babs630', 'Babs880', 'Babs950', 'BabsBrC340',
        'BabsBrC370', 'BabsBrC400', 'BabsBrC470', 'BabsBrC520',
        'BabsBrC590', 'BabsBrC630', 'BabsBrC880', 'BabsBrC950',
        'BrC', 'Pressure', 'Temp', 'Flow1',
        'Flow2', 'FlowC', 'PumpDriver', 'PumpSpeed',
        'ControllerTemp', 'InletHumidity', 'InletTemp', 'TapeHumidity',
        'TapeTemp', 'LedTemp', 'LedSourceTemp', 'TapeAdvanceCount',
        'TapeAdvanceLeft', 'CPU',
    ],
    'DebugView': [
        'ID', 'TimestampUTC', 'TimestampLocal', 'G0_Status',
        'G1_Status', 'G2_Status', 'G3_Status', 'G4_Status',
        'G5_Status', 'G6_Status', 'ControllerFW', 'ControllerSync',
        'ControllerStatus', 'ControllerTemp', 'DetectorVoltage', 'DriverVoltage',
        'DoorPosition', 'FanSpeed', 'TapeAdvanceStatus', 'ChamberStatus',
        'ValveStatus', 'PumpStatus', 'TapeLeftRAW', 'TapeRightRAW',
        'TapePulsesLeft', 'TapePulsesRight', 'FlowCRAW', 'Flow1RAW',
        'FlowRef', 'PumpDriver', 'PumpSpeed', 'InletHumidity',
        'InletTemp', 'DetectorFW', 'DetectorSync', 'DetectorStatus',
        'TapeHumidity', 'TapeTemp', 'ChamberPosition', 'Ref340',
        'Sens340_1', 'Sens340_2', 'Ref370', 'Sens370_1',
        'Sens370_2', 'Ref400', 'Sens400_1', 'Sens400_2',
        'Ref470', 'Sens470_1', 'Sens470_2', 'Ref520',
        'Sens520_1', 'Sens520_2', 'Ref590', 'Sens590_1',
        'Sens590_2', 'Ref630', 'Sens630_1', 'Sens630_2',
        'Ref880', 'Sens880_1', 'Sens880_2', 'Ref950',
        'Sens950_1', 'Sens950_2', 'DetectorStatusCh340', 'DetectorStatusCh370',
        'DetectorStatusCh400', 'DetectorStatusCh470', 'DetectorStatusCh520', 'DetectorStatusCh590',
        'DetectorStatusCh630', 'DetectorStatusCh880', 'DetectorStatusCh950', 'LedFW',
        'LedSync', 'LedStatus', 'LedTemp', 'LedSourceTemp',
        'LedCurrentCh340', 'LedCurrentCh370', 'LedCurrentCh400', 'LedCurrentCh470',
        'LedCurrentCh520', 'LedCurrentCh590', 'LedCurrentCh630', 'LedCurrentCh880',
        'LedCurrentCh950', 'LedStatusCh340', 'LedStatusCh370', 'LedStatusCh400',
        'LedStatusCh470', 'LedStatusCh520', 'LedStatusCh590', 'LedStatusCh630',
        'LedStatusCh880', 'LedStatusCh950', 'Pressure', 'Temp',
        'CPU', 'DiskSpace', 'NumConnections',
    ],
    'LogView': ['ID', 'Timestamp', 'ClassName', 'Method', 'Message'],
}


COLUMNS_TCA09 = {
    'Data': [
        'ID', 'SampleID', 'SampleStartTimeUTC', 'SampleStartTimeLocal',
        'SampleEndTimeUTC', 'SampleEndTimeLocal', 'AnalysisStartTimeUTC', 'AnalysisStartTimeLocal',
        'AnalysisEndTimeUTC', 'AnalysisEndTimeLocal', 'SetupID', 'SettingsID',
        'SampleName', 'PunchArea', 'DryingTime', 'G0_Status',
        'G1_Status', 'G2_Status', 'G3_Status', 'G4_Status',
        'G5_Status', 'G6_Status', 'G7_Status', 'Chamber',
        'FilterIntegrity', 'TC_Counts', 'Zero_Counts', 'TCmass',
        'TCconc_surface', 'TCconc_volume', 'SampleFlow', 'AnalyticFlow',
        'Volume', 'Pressure', 'Temp', 'BC880',
        'BB', 'POC', 'SOC', 'BC_ValidData',
        'b', 'OC', 'EC', 'CO2',
        'NDIR_Temp', 'NDIR_Pressure', 'NDIR_CO2', 'NDIR_CO2abs',
        'NDIR_H2O', 'NDIR_H2Oabs', 'NDIR_H2Odewpoint', 'NDIR_Voltage',
        'SamplePumpDriver', 'AnalyticPumpDriver', 'SamplePumpSpeed', 'AnalyticPumpSpeed',
        'Ch1MaxTemp', 'Ch2MaxTemp', 'InternalTemp', 'CPU',
        'DBsize', 'NumConnections', 'PolyA0', 'PolyA1',
        'PolyA2', 'PolyA3', 'PolyA4', 'PolyA5',
        'PolyB0', 'PolyB1', 'PolyB2', 'PolyB3',
        'PolyB4', 'PolyB5', 'TCconc_volume_CleanAir', 'AnalysisType',
        'BCff', 'BCbb', 'POCff', 'POCbb',
        'ECff', 'ECbb',
    ],
    'DatabaseVer': ['ID', 'TimestampLocal', 'Version'],
    'DateOrder': ['ID', 'Date', 'FirstID', 'LastID'],
    'DebugData': [
        'ID', 'TimestampUTC', 'TimestampLocal', 'SetupID',
        'SettingsID', 'G0_Status', 'G1_Status', 'G2_Status',
        'G3_Status', 'G4_Status', 'G5_Status', 'G6_Status',
        'G7_Status', 'Ch1_Analysis', 'Ch1_Status', 'Ch1_SampleID',
        'Ch2_Status', 'Ch2_Analysis', 'Ch2_SampleID', 'Ack',
        'ReturnHeartbeat', 'Heartbeat', 'FW_Status', 'FW_LicorStatus',
        'FW_ErrorStatus', 'Beeper', 'AnalyticPumpFlow', 'AnalyticPumpSet',
        'AnalyticPumpFlowRAW', 'AnalyticPumpSpeed', 'AnalyticPumpDriver', 'SamplePumpFlow',
        'SamplePumpSet', 'SamplePumpFlowRAW', 'SamplePumpSpeed', 'SamplePumpDriver',
        'SamplePumpStatus', 'Pressure', 'Temp', 'SV12',
        'SV22', 'SV30', 'SV31', 'SV32',
        'SV33', 'BV11', 'BV21', 'BV31',
        'SelectedChamber', 'Heater1SetPWM', 'Heater1Voltage', 'Heater1Current',
        'Heater1Driver', 'Heater1Status', 'Heater1Error', 'Heater2SetPWM',
        'Heater2Voltage', 'Heater2Current', 'Heater2Driver', 'Heater2Status',
        'Heater2Error', 'Ch1Temp', 'Ch2Temp', 'PowerBoardTemp1',
        'PowerBoardTemp2', 'PCB_Ch1Temp', 'PCB_Ch2Temp', 'NTC_Ch1Temp',
        'NTC_Ch2Temp', 'LockStatus', 'SetFan1', 'Fan1',
        'SetFan2', 'Fan2', 'SetFan3', 'Fan3',
        'NDIR_Temp', 'NDIR_Pressure', 'NDIR_CO2', 'NDIR_CO2abs',
        'NDIR_H2O', 'NDIR_H2Oabs', 'NDIR_H2Odewpoint', 'CPU',
        'RAM', 'CPU_Temp', 'DBsize', 'NumConnections',
        'Reserved1', 'Reserved2', 'Reserved3', 'Reserved4',
        'Reserved5', 'Reserved6', 'Reserved7', 'Reserved8',
        'Reserved9',
    ],
    'ExtDeviceAvgData': [
        'ID', 'DataID', 'SampleID', 'SampleStartTimeUTC',
        'SampleStartTimeLocal', 'SampleEndTimeUTC', 'SampleEndTimeLocal', 'DeviceID',
        'Validity', 'DeviceData',
    ],
    'ExtDeviceData': ['ID', 'TimestampLocal', 'DebugDataID', 'DeviceID', 'DeviceData'],
    'ExtDeviceSetup': ['ID', 'TimestampLocal', 'DebugDataID', 'DeviceID1', 'DeviceID2', 'DeviceID3'],
    'HeaterResistance': [
        'ID', 'TimestampLocal', 'SampleID', 'R_Ch1_1',
        'R_Ch1_2', 'R_Ch2_1', 'R_Ch2_2', 'U11',
        'U12', 'U13', 'U21', 'U22',
        'U23',
    ],
    'Log': ['ID', 'TimestampLocal', 'Severity', 'MessageID', 'Message'],
    'MaintenanceData': ['ID', 'TimestampUTC', 'MaintenanceID', 'Value'],
    'Settings': [
        'ID', 'SerialNumber', 'TimestampLocal', 'Language',
        'DHCP', 'InstrumentIP', 'SubnetMask', 'Gateway',
        'DNS', 'HomeChartPeriod', 'RasEnabled', 'AdpEnabled',
        'AeroBaudRate', 'AeroDelimiter', 'UidepEnabled', 'BHparamID',
        'BHBaudRate', 'ModBusID', 'ModBusBaudRate', 'Display',
        'HomeChartData', 'ModBusEnabled',
    ],
    'Setup': [
        'ID', 'SerialNumber', 'TimestampLocal', 'FirmwareVersion',
        'SoftwareVersion', 'SystemVersion', 'Timebase', 'Area',
        'SetFlowS', 'SetFlowA', 'FlowSa0', 'FlowSa1',
        'FlowSa2', 'FlowAa0', 'FlowAa1', 'FlowAa2',
        'CCch1', 'CCch2', 'SlopeTempCh1', 'InterceptTempCh1',
        'SlopeTempCh2', 'InterceptTempCh2', 'C0', 'C1',
        'C2', 'C3', 'C4', 'C5',
        'C6', 'P11', 'P12', 'P13',
        'P21', 'P22', 'P23', 'PS1a0',
        'PS1a1', 'PS1a2', 'PS1a3', 'PS2a0',
        'PS2a1', 'PS2a2', 'PS2a3', 'A0',
        'A2', 'A3', 'FlowRepStd', 'Pressure',
        'Temp', 'CleanAirTestEnabled', 'CleanAirTestType', 'CleanAirTestDay',
        'CleanAirTestTime', 'CleanAirLimit', 'b', 'DST',
        'TimeZone', 'TimeSync', 'FilterIntegrityThreshold', 'NTPserver',
        'CleanChambers', 'HeaterSavingMode', 'HeaterSavingModeCount', 'NDIRSerialNumber',
        'OC_BC_PrimaryRatio_ff', 'OC_BC_PrimaryRatio_bb', 'LeakageTest',
    ],
    'TestReports': ['ID', 'TimestampLocal', 'Type', 'Passed', 'Report'],
    'sqlite_sequence': ['name', 'seq'],
    'DataView': [
        'ID', 'SampleID', 'SampleStartTimeUTC', 'SampleStartTimeLocal',
        'SampleEndTimeUTC', 'SampleEndTimeLocal', 'AnalysisStartTimeUTC', 'AnalysisStartTimeLocal',
        'AnalysisEndTimeUTC', 'AnalysisEndTimeLocal', 'TCconc_volume', 'TCconc_volume_CleanAir',
        'G0_Status', 'G1_Status', 'G2_Status', 'G3_Status',
        'G4_Status', 'G5_Status', 'G6_Status', 'G7_Status',
        'AnalysisType', 'BC880', 'BC_ValidData', 'BB',
        'BCff', 'BCbb', 'b', 'OC',
        'EC', 'ECff', 'ECbb', 'POC',
        'POCff', 'POCbb', 'SOC', 'SampleName',
        'TCconc_surface', 'PunchArea', 'TCmass', 'DryingTime',
        'TC_Counts', 'Zero_Counts', 'Chamber', 'FilterIntegrity',
        'SampleFlow', 'AnalyticFlow', 'Volume', 'Pressure',
        'Temp', 'SetupID', 'SettingsID', 'CO2',
        'NDIR_Temp', 'NDIR_Pressure', 'NDIR_CO2', 'NDIR_CO2abs',
        'NDIR_H2O', 'NDIR_H2Oabs', 'NDIR_H2Odewpoint', 'NDIR_Voltage',
        'SamplePumpDriver', 'AnalyticPumpDriver', 'SamplePumpSpeed', 'AnalyticPumpSpeed',
        'Ch1MaxTemp', 'Ch2MaxTemp', 'InternalTemp', 'CPU',
        'DBsize', 'NumConnections', 'PolyA0', 'PolyA1',
        'PolyA2', 'PolyA3', 'PolyA4', 'PolyA5',
        'PolyB0', 'PolyB1', 'PolyB2', 'PolyB3',
        'PolyB4', 'PolyB5',
    ],
    'DatabaseVerView': ['ID', 'TimestampLocal', 'Version'],
    'DebugDataView': [
        'ID', 'TimestampUTC', 'TimestampLocal', 'SetupID',
        'SettingsID', 'G0_Status', 'G1_Status', 'G2_Status',
        'G3_Status', 'G4_Status', 'G5_Status', 'G6_Status',
        'G7_Status', 'Ch1_Analysis', 'Ch1_Status', 'Ch1_SampleID',
        'Ch2_Status', 'Ch2_Analysis', 'Ch2_SampleID', 'Ack',
        'ReturnHeartbeat', 'Heartbeat', 'FW_Status', 'FW_LicorStatus',
        'FW_ErrorStatus', 'Beeper', 'AnalyticPumpFlow', 'AnalyticPumpSet',
        'AnalyticPumpFlowRAW', 'AnalyticPumpSpeed', 'AnalyticPumpDriver', 'SamplePumpFlow',
        'SamplePumpSet', 'SamplePumpFlowRAW', 'SamplePumpSpeed', 'SamplePumpDriver',
        'SamplePumpStatus', 'Pressure', 'Temp', 'SV12',
        'SV22', 'SV30', 'SV31', 'SV32',
        'SV33', 'BV11', 'BV21', 'BV31',
        'SelectedChamber', 'Heater1SetPWM', 'Heater1Voltage', 'Heater1Current',
        'Heater1Driver', 'Heater1Status', 'Heater1Error', 'Heater2Voltage',
        'Heater2SetPWM', 'Heater2Current', 'Heater2Driver', 'Heater2Status',
        'Heater2Error', 'Ch1Temp', 'Ch2Temp', 'PCB_Ch1Temp',
        'PCB_Ch2Temp', 'NTC_Ch1Temp', 'NTC_Ch2Temp', 'PowerBoardTemp1',
        'PowerBoardTemp2', 'LockStatus', 'SetFan1', 'Fan1',
        'SetFan2', 'Fan2', 'SetFan3', 'Fan3',
        'NDIR_Temp', 'NDIR_Pressure', 'NDIR_CO2', 'NDIR_CO2abs',
        'NDIR_H2O', 'NDIR_H2Oabs', 'NDIR_H2Odewpoint', 'CPU',
        'RAM', 'CPU_Temp', 'DBsize', 'NumConnections',
        'Reserved1', 'Reserved2', 'Reserved3', 'Reserved4',
        'Reserved5', 'Reserved6', 'Reserved7', 'Reserved8',
        'Reserved9',
    ],
    'ExtDeviceAvgDataView': [
        'ID', 'DataID', 'SampleID', 'SampleStartTimeUTC',
        'SampleStartTimeLocal', 'SampleEndTimeUTC', 'SampleEndTimeLocal', 'DeviceID',
        'Validity', 'DeviceData',
    ],
    'ExtDeviceDataView': ['ID', 'TimestampLocal', 'DebugDataID', 'DeviceID', 'DeviceData'],
    'ExtDeviceSetupView': ['ID', 'TimestampLocal', 'DebugDataID', 'DeviceID1', 'DeviceID2', 'DeviceID3'],
    'HeaterResistanceView': [
        'ID', 'TimestampLocal', 'SampleID', 'R_Ch1_1',
        'R_Ch1_2', 'R_Ch2_1', 'R_Ch2_2', 'U11',
        'U12', 'U13', 'U21', 'U22',
        'U23',
    ],
    'LogView': ['ID', 'TimestampLocal', 'Severity', 'MessageID', 'Message'],
    'MaintenanceDataView': ['ID', 'TimestampUTC', 'MaintenanceID', 'Description', 'Value'],
    'OfflineDataView': [
        'ID', 'SampleID', 'AnalysisStartTimeUTC', 'AnalysisStartTimeLocal',
        'AnalysisEndTimeUTC', 'AnalysisEndTimeLocal', 'G0_Status', 'G1_Status',
        'G2_Status', 'G3_Status', 'G4_Status', 'G5_Status',
        'G6_Status', 'G7_Status', 'SampleName', 'TCconc_surface',
        'PunchArea', 'TCmass', 'DryingTime', 'TC_Counts',
        'Zero_Counts', 'Chamber', 'FilterIntegrity', 'AnalyticFlow',
        'SetupID', 'SettingsID', 'CO2',
    ],
    'OnlineDataView': [
        'ID', 'SampleID', 'SampleStartTimeUTC', 'SampleStartTimeLocal',
        'SampleEndTimeUTC', 'SampleEndTimeLocal', 'AnalysisStartTimeUTC', 'AnalysisStartTimeLocal',
        'AnalysisEndTimeUTC', 'AnalysisEndTimeLocal', 'TCconc_volume', 'TCconc_volume_CleanAir',
        'G0_Status', 'G1_Status', 'G2_Status', 'G3_Status',
        'G4_Status', 'G5_Status', 'G6_Status', 'G7_Status',
        'AnalysisType', 'BC880', 'BC_ValidData', 'BB',
        'BCff', 'BCbb', 'b', 'OC',
        'EC', 'ECff', 'ECbb', 'POC',
        'POCff', 'POCbb', 'SOC', 'TCconc_surface',
        'PunchArea', 'TCmass', 'TC_Counts', 'Zero_Counts',
        'Chamber', 'FilterIntegrity', 'SampleFlow', 'AnalyticFlow',
        'Volume', 'Pressure', 'Temp', 'SetupID',
        'SettingsID', 'CO2',
    ],
    'SettingsView': [
        'ID', 'TimestampLocal', 'SerialNumber', 'Language',
        'DHCP', 'InstrumentIP', 'SubnetMask', 'Gateway',
        'DNS', 'HomeChartPeriod', 'HomeChartData', 'Display',
        'RasEnabled', 'AdpEnabled', 'AeroBaudRate', 'AeroDelimiter',
        'UidepEnabled', 'BHparamID', 'BHBaudRate', 'ModBusID',
        'ModBusBaudRate', 'ModBusEnabled',
    ],
    'SetupView': [
        'ID', 'TimestampLocal', 'SerialNumber', 'NDIRSerialNumber',
        'FirmwareVersion', 'SoftwareVersion', 'SystemVersion', 'Timebase',
        'Area', 'SetFlowS', 'SetFlowA', 'FlowSa0',
        'FlowSa1', 'FlowSa2', 'FlowAa0', 'FlowAa1',
        'FlowAa2', 'CCch1', 'CCch2', 'SlopeTempCh1',
        'InterceptTempCh1', 'SlopeTempCh2', 'InterceptTempCh2', 'C0',
        'C1', 'C2', 'C3', 'C4',
        'C5', 'C6', 'P11', 'P12',
        'P13', 'P21', 'P22', 'P23',
        'PS1a0', 'PS1a1', 'PS1a2', 'PS1a3',
        'PS2a0', 'PS2a1', 'PS2a2', 'PS2a3',
        'A0', 'A2', 'A3', 'FlowRepStd',
        'Pressure', 'Temp', 'OC_BC_PrimaryRatio_ff', 'OC_BC_PrimaryRatio_bb',
        'CleanAirTestEnabled', 'CleanAirTestType', 'CleanAirTestDay', 'CleanAirTestTime',
        'CleanAirLimit', 'CleanChambers', 'HeaterSavingMode', 'HeaterSavingModeCount',
        'LeakageTest', 'b', 'DST', 'TimeZone',
        'TimeSync', 'FilterIntegrityThreshold', 'NTPserver',
    ],
    'TestReportsView': ['ID', 'TimestampLocal', 'Type', 'Passed', 'Report'],
}


COLUMNS_TCA08 = {
    'Data': [
        'ID', 'TimeStamp', 'SetupID', 'Timebase',
        'G0_Status', 'G1_Status', 'G2_Status', 'G3_Status',
        'G4_Status', 'G5_Status', 'G6_Status', 'Ch1_Status',
        'Ch1_SampleID', 'Ch2_Status', 'Ch2_SampleID', 'MainBoardStatus',
        'Ch1BoardStatus', 'Ch2BoardStatus', 'SensorBoardStatus', 'FlowS',
        'setFlowS', 'FlowS_RAW', 'SamplePumpSpeed', 'FlowA',
        'setFlowA', 'FlowA_RAW', 'AnalyticPumpSpeed', 'Solenoid1',
        'Solenoid2', 'Solenoid5', 'BallValve1', 'BallValve2',
        'BallValve3', 'BallValve4', 'Ch1_Temp', 'Ch2_Temp',
        'Ch1_Voltage1', 'setCh1Voltage1', 'Ch1_Current1', 'Ch1_Voltage2',
        'setCh1Voltage2', 'Ch1_Current2', 'Ch2_Voltage1', 'setCh2Voltage1',
        'Ch2_Current1', 'Ch2_Voltage2', 'setCh2Voltage2', 'Ch2_Current2',
        'Ch1_SafetyTemp', 'Ch2_SafetyTemp', 'SafetyTempInt', 'Fan1',
        'Fan2', 'Fan3', 'Fan4', 'LicorTemp',
        'LicorPressure', 'LicorCO2', 'LicorCO2abs', 'LicorH2O',
        'LicorH2Oabs', 'LicorH2Odewpoint', 'LicorVoltage', 'CPU',
        'RAM', 'CPU_TEMP',
    ],
    'DatabaseVer': ['ID', 'TimeStamp', 'Version'],
    'DateOrder': ['ID', 'Date', 'FirstID', 'LastID'],
    'ExtDeviceData': ['ID', 'DataID', 'DeviceID', 'DeviceData'],
    'ExtDeviceSetup': [
        'ID', 'DataID', 'DeviceID1', 'DeviceID2',
        'DeviceID3', 'DeviceID4', 'DeviceID5', 'DeviceID6',
    ],
    'FilterIntegrity': ['ID', 'SampleID', 'Chamber', 'p1', 'p2', 'dp'],
    'HeaterResistance': [
        'ID', 'TimeStamp', 'SampleID', 'R_Ch1_1',
        'R_Ch1_2', 'R_Ch2_1', 'R_Ch2_2', 'U11',
        'U12', 'U13', 'U21', 'U22',
        'U23',
    ],
    'Log': ['ID', 'TimeStamp', 'Severity', 'MessageID', 'Message'],
    'OfflineResult': [
        'ID', 'SampleID', 'SampleName', 'StartTimeUTC',
        'StartTimeLocal', 'TCcounts', 'TCmass', 'TCconc',
        'PunchArea', 'DryingTime', 'Chamber', 'SetupID',
        'a1', 'b1', 'c1', 'd1',
        'e1', 'f1', 'a2', 'b2',
        'c2', 'd2', 'e2', 'f2',
    ],
    'OnlineResult': [
        'ID', 'SampleID', 'StartTimeUTC', 'EndTimeUTC',
        'StartTimeLocal', 'EndTimeLocal', 'TCcounts', 'TCmass',
        'TCconc', 'AE33_BC6', 'AE33_ValidData', 'AE33_b',
        'OC', 'EC', 'CO2', 'Volume',
        'Chamber', 'SetupID', 'a1', 'b1',
        'c1', 'd1', 'e1', 'f1',
        'a2', 'b2', 'c2', 'd2',
        'e2', 'f2',
    ],
    'SamplerData': ['ID', 'Timestamp', 'SampleID', 'SamplerSetFlow', 'SamplerFlow'],
    'SamplerResults': ['ID', 'SampleID', 'SampleName', 'StartTime', 'EndTime', 'TCA08conc', 'AverageFlow'],
    'Setup': [
        'ID', 'TimeStamp', 'SerialNumber', 'SetFlowS',
        'SetFlowA', 'Area', 'FlowFormulaA', 'FlowFormulaB',
        'FlowFormulaC', 'FlowFormulaD', 'FlowFormulaE', 'FlowFormulaF',
        'CCch1', 'CCch2', 'SlopeTempCh1', 'InterceptTempCh1',
        'SlopeTempCh2', 'InterceptTempCh2', 'SampleTime', 'C0',
        'C1', 'C2', 'C3', 'C4',
        'C5', 'C6', 'C7', 'C8',
        'C9', 'C10', 'P11', 'P12',
        'P13', 'P21', 'P22', 'P23',
        'A0', 'A2', 'A3', 'FlowRepStd',
        'Temp', 'Pressure', 'SoftwareVersion', 'FirmwareVersion',
        'AE33_b', 'TimeZone', 'DST', 'TimeProtocol',
        'BHparamID', 'FilterIntegrity_threshold', 'DHCP', 'InstrumentIP',
        'SubnetMask', 'Gateway', 'BHBaudRate', 'ModBusID',
        'ModBusBaudRate', 'AeroBaudRate', 'AeroDelimiter', 'AdpEnabled',
        'UidepEnabled', 'RasEnabled',
    ],
    'TestReports': ['ID', 'TimeStamp', 'ReportType', 'Passed', 'Report'],
    'sqlite_sequence': ['name', 'seq'],
}

COLUMNS_AE33 = {
    'Data': [
        'SerialNumber', 'ID', 'StartTime', 'EndTime',
        'SetupID', 'SetupTimestamp', 'Ref1', 'Sens11',
        'Sens12', 'Ref2', 'Sens21', 'Sens22',
        'Ref3', 'Sens31', 'Sens32', 'Ref4',
        'Sens41', 'Sens42', 'Ref5', 'Sens51',
        'Sens52', 'Ref6', 'Sens61', 'Sens62',
        'Ref7', 'Sens71', 'Sens72', 'BC11',
        'BC12', 'BC1', 'BC21', 'BC22',
        'BC2', 'BC31', 'BC32', 'BC3',
        'BC41', 'BC42', 'BC4', 'BC51',
        'BC52', 'BC5', 'BC61', 'BC62',
        'BC6', 'BC71', 'BC72', 'BC7',
        'K1', 'K2', 'K3', 'K4',
        'K5', 'K6', 'K7', 'BB',
        'Pressure', 'Temp', 'Flow1', 'Flow2',
        'FlowC', 'T_controller', 'T_supply', 'T_LED',
        'ControllerStatus', 'LEDStatus', 'DetectorStatus', 'ValveStatus',
        'Status', 'TapeAdvanceCount', 'TapeAdvanceLeft', 'CPU',
        'DiskSpace', 'NumConnections',
    ],
    'ExtDeviceData': ['SerialNumber', 'ID', 'DataID', 'DeviceID', 'DeviceData'],
    'Setup': [
        'serial', 'ID', 'SerialNumber', 'Timestamp',
        'FirmwareVer', 'SoftwareVer', 'DataCenterIP', 'AutoConnect',
        'InletFilter', 'Timebase', 'SG1', 'SG2',
        'SG3', 'SG4', 'SG5', 'SG6',
        'SG7', 'C', 'Area', 'Zeta',
        'Aff', 'Abb', 'Pressure', 'Temp',
        'ATNf1', 'ATNf2', 'Kmax', 'Kmin',
        'Flow', 'FlowRepStd', 'PumpPresetValue', 'FlowFormulaA0',
        'FlowFormulaA1', 'FlowFormulaB0', 'FlowFormulaB1', 'FlowFormulaC0',
        'FlowFormulaC1', 'FlowFormulaD', 'FlowFormulaE', 'FlowFormulaF',
        'TAtype', 'TAatnMax', 'TAinterval', 'TAtime',
        'TapeRightFormulaK', 'TapeRightFormulaN', 'TapeLeftFormulaK', 'TapeLeftFormulaN',
        'WarmUpInterval', 'AutoTestEnabled', 'AutoTestType', 'AutoTestDay',
        'AutoTestTime', 'MeasureTimeStamp', 'HomeInfo', 'Display',
        'About', 'DST', 'TimeZone', 'TapeAdvanceAdjust',
        'ExternalID', 'BHparamID', 'TimeSync', 'DHCP',
        'InstrumentIP', 'SubnetMask', 'Gateway', 'Baud',
        'NTPserver',
    ],
    'TestReports': ['ID', 'Type', 'Timestamp', 'Passed', 'Report'],
    'Log': ['ID', 'Timestamp', 'Severity', 'ClassID', 'MethodID', 'MessageID', 'Message'],
    'Message': ['ID', 'Message'],
    'Method': ['ID', 'Name'],
    'NDTest': [
        'ID', 'FilterSetSN', 'Timestamp', 'Reference',
        'ch1s1f0', 'ch1s2f0', 'ch2s1f0', 'ch2s2f0',
        'ch3s1f0', 'ch3s2f0', 'ch4s1f0', 'ch4s2f0',
        'ch5s1f0', 'ch5s2f0', 'ch6s1f0', 'ch6s2f0',
        'ch7s1f0', 'ch7s2f0', 'ch1s1f1', 'ch1s2f1',
        'ch2s1f1', 'ch2s2f1', 'ch3s1f1', 'ch3s2f1',
        'ch4s1f1', 'ch4s2f1', 'ch5s1f1', 'ch5s2f1',
        'ch6s1f1', 'ch6s2f1', 'ch7s1f1', 'ch7s2f1',
        'ch1s1f2', 'ch1s2f2', 'ch2s1f2', 'ch2s2f2',
        'ch3s1f2', 'ch3s2f2', 'ch4s1f2', 'ch4s2f2',
        'ch5s1f2', 'ch5s2f2', 'ch6s1f2', 'ch6s2f2',
        'ch7s1f2', 'ch7s2f2', 'ch1s1f3', 'ch1s2f3',
        'ch2s1f3', 'ch2s2f3', 'ch3s1f3', 'ch3s2f3',
        'ch4s1f3', 'ch4s2f3', 'ch5s1f3', 'ch5s2f3',
        'ch6s1f3', 'ch6s2f3', 'ch7s1f3', 'ch7s2f3',
    ],
    'ClassName': ['ID', 'Name'],
    'FilterSet': [
        'ID', 'FilterSetSN', 'Timestamp', 'ch1s1f0',
        'ch1s2f0', 'ch2s1f0', 'ch2s2f0', 'ch3s1f0',
        'ch3s2f0', 'ch4s1f0', 'ch4s2f0', 'ch5s1f0',
        'ch5s2f0', 'ch6s1f0', 'ch6s2f0', 'ch7s1f0',
        'ch7s2f0', 'ch1s1f1', 'ch1s2f1', 'ch2s1f1',
        'ch2s2f1', 'ch3s1f1', 'ch3s2f1', 'ch4s1f1',
        'ch4s2f1', 'ch5s1f1', 'ch5s2f1', 'ch6s1f1',
        'ch6s2f1', 'ch7s1f1', 'ch7s2f1', 'ch1s1f2',
        'ch1s2f2', 'ch2s1f2', 'ch2s2f2', 'ch3s1f2',
        'ch3s2f2', 'ch4s1f2', 'ch4s2f2', 'ch5s1f2',
        'ch5s2f2', 'ch6s1f2', 'ch6s2f2', 'ch7s1f2',
        'ch7s2f2', 'ch1s1f3', 'ch1s2f3', 'ch2s1f3',
        'ch2s2f3', 'ch3s1f3', 'ch3s2f3', 'ch4s1f3',
        'ch4s2f3', 'ch5s1f3', 'ch5s2f3', 'ch6s1f3',
        'ch6s2f3', 'ch7s1f3', 'ch7s2f3',
    ],
    'ExtDeviceSetup': ['ID', 'Timestamp', 'DeviceID1', 'DeviceID2', 'DeviceID3'],
    'DateOrder': ['ID', 'Date', 'StartID', 'EndID'],
}
