# Copyright (c) 2026 Aerosol d.o.o.
# Licensed under the Aerosol Magee Scientific Software License
# (see LICENSE file for details)

TABLES2SYNC_AE36S = ['Data', 'Setup', 'Log', 'DateOrder', 'ExtDeviceData', 'ExtDeviceSetup']
# TABLES2SYNC_AE36S = ['DataView', 'Setup', 'LogView', 'DateOrder', 'ExtDeviceData', 'ExtDeviceSetup']
TABLES2SYNC_TCA09 = ['Data', 'Setup', 'Settings', 'Log', 'DateOrder', 'ExtDeviceAvgData', 'ExtDeviceSetup',
                     'MaintenanceData', 'HeaterResistance']
# TABLES2SYNC_TCA09 = ['DataView', 'SetupView', 'SettingsView', 'LogView', 'DateOrder', 'ExtDeviceAvgDataView',
#                      'ExtDeviceSetupView', 'MaintenanceDataView', 'HeaterResistanceView']
TABLES2SYNC_TCA08 = ['OnlineResult', 'Setup', 'Log', 'DateOrder', 'ExtDeviceData', 'ExtDeviceSetup',
                     'FilterIntegrity', 'HeaterResistance']
TABLES2SYNC_AE33 = ['Data', 'Setup', 'Log', 'ExtDeviceData', 'ExtDeviceSetup', 'DateOrder']

COLUMNS_AE36S = {
    'BCindex': {
        'ID': 'INTEGER', 'DataID': 'INTEGER', 'BC880_1H': 'INTEGER', 'Validity_1H': 'DECIMAL',
        'Babs470_1H': 'DECIMAL', 'Babs950_1H': 'DECIMAL', 'BCff_1H': 'DECIMAL', 'BCbb_1H': 'DECIMAL',
        'BC880_24H': 'INTEGER', 'Validity_24H': 'DECIMAL', 'BCindex': 'INTEGER', 'BCff_24H': 'DECIMAL',
        'BCbb_24H': 'DECIMAL',
    },
    'ClassName': {
        'ID': 'INTEGER', 'Name': 'nvarchar(100)',
    },
    'Data': {
        'ID': 'INTEGER', 'TimestampUTC': 'BIGINT', 'TimestampLocal': 'BIGINT', 'SetupID': 'INT',
        'G0_Status': 'INT', 'G1_Status': 'INT', 'G2_Status': 'INT', 'G3_Status': 'INT',
        'G4_Status': 'INT', 'G5_Status': 'INT', 'G6_Status': 'INT', 'ControllerStatus': 'SMALLINT',
        'DetectorStatus': 'SMALLINT', 'LedStatus': 'SMALLINT', 'ValveStatus': 'SMALLINT', 'PumpStatus': 'SMALLINT',
        'Ref340': 'REAL', 'Sens340_1': 'REAL', 'Sens340_2': 'REAL', 'Ref370': 'REAL',
        'Sens370_1': 'REAL', 'Sens370_2': 'REAL', 'Ref400': 'REAL', 'Sens400_1': 'REAL',
        'Sens400_2': 'REAL', 'Ref470': 'REAL', 'Sens470_1': 'REAL', 'Sens470_2': 'REAL',
        'Ref520': 'REAL', 'Sens520_1': 'REAL', 'Sens520_2': 'REAL', 'Ref590': 'REAL',
        'Sens590_1': 'REAL', 'Sens590_2': 'REAL', 'Ref630': 'REAL', 'Sens630_1': 'REAL',
        'Sens630_2': 'REAL', 'Ref880': 'REAL', 'Sens880_1': 'REAL', 'Sens880_2': 'REAL',
        'Ref950': 'REAL', 'Sens950_1': 'REAL', 'Sens950_2': 'REAL', 'Atn340_1': 'DECIMAL',
        'Atn340_2': 'DECIMAL', 'Atn370_1': 'DECIMAL', 'Atn370_2': 'DECIMAL', 'Atn400_1': 'DECIMAL',
        'Atn400_2': 'DECIMAL', 'Atn470_1': 'DECIMAL', 'Atn470_2': 'DECIMAL', 'Atn520_1': 'DECIMAL',
        'Atn520_2': 'DECIMAL', 'Atn590_1': 'DECIMAL', 'Atn590_2': 'DECIMAL', 'Atn630_1': 'DECIMAL',
        'Atn630_2': 'DECIMAL', 'Atn880_1': 'DECIMAL', 'Atn880_2': 'DECIMAL', 'Atn950_1': 'DECIMAL',
        'Atn950_2': 'DECIMAL', 'BC340_1': 'INT', 'BC340_2': 'INT', 'BC340': 'INT',
        'BC370_1': 'INT', 'BC370_2': 'INT', 'BC370': 'INT', 'BC400_1': 'INT',
        'BC400_2': 'INT', 'BC400': 'INT', 'BC470_1': 'INT', 'BC470_2': 'INT',
        'BC470': 'INT', 'BC520_1': 'INT', 'BC520_2': 'INT', 'BC520': 'INT',
        'BC590_1': 'INT', 'BC590_2': 'INT', 'BC590': 'INT', 'BC630_1': 'INT',
        'BC630_2': 'INT', 'BC630': 'INT', 'BC880_1': 'INT', 'BC880_2': 'INT',
        'BC880': 'INT', 'BC950_1': 'INT', 'BC950_2': 'INT', 'BC950': 'INT',
        'K340': 'DECIMAL', 'K370': 'DECIMAL', 'K400': 'DECIMAL', 'K470': 'DECIMAL',
        'K520': 'DECIMAL', 'K590': 'DECIMAL', 'K630': 'DECIMAL', 'K880': 'DECIMAL',
        'K950': 'DECIMAL', 'BB': 'DECIMAL', 'Babs340': 'DECIMAL', 'Babs370': 'DECIMAL',
        'Babs400': 'DECIMAL', 'Babs470': 'DECIMAL', 'Babs520': 'DECIMAL', 'Babs590': 'DECIMAL',
        'Babs630': 'DECIMAL', 'Babs880': 'DECIMAL', 'Babs950': 'DECIMAL', 'BabsBrC340': 'DECIMAL',
        'BabsBrC370': 'DECIMAL', 'BabsBrC400': 'DECIMAL', 'BabsBrC470': 'DECIMAL', 'BabsBrC520': 'DECIMAL',
        'BabsBrC590': 'DECIMAL', 'BabsBrC630': 'DECIMAL', 'BabsBrC880': 'DECIMAL', 'BabsBrC950': 'DECIMAL',
        'BrC': 'INT', 'Pressure': 'INTEGER', 'Temp': 'DECIMAL', 'Flow1': 'SMALLINT',
        'Flow2': 'SMALLINT', 'FlowC': 'SMALLINT', 'PumpDriver': 'SMALLINT', 'PumpSpeed': 'SMALLINT',
        'ControllerTemp': 'DECIMAL', 'InletHumidity': 'DECIMAL', 'InletTemp': 'DECIMAL', 'TapeHumidity': 'DECIMAL',
        'TapeTemp': 'DECIMAL', 'LedTemp': 'DECIMAL', 'LedSourceTemp': 'SMALLINT', 'TapeAdvanceCount': 'INT',
        'TapeAdvanceLeft': 'SMALLINT', 'CPU': 'TINYINT',
    },
    'DataBaseVersion': {
        'Version': 'nvarchar(100)',
    },
    'DateOrder': {
        'ID': 'INTEGER', 'Date': 'DATE', 'StartID': 'INT', 'EndID': 'INT',
    },
    'Debug': {
        'ID': 'INTEGER', 'TimestampUTC': 'BIGINT', 'TimestampLocal': 'BIGINT', 'G0_Status': 'INTEGER',
        'G1_Status': 'INTEGER', 'G2_Status': 'INTEGER', 'G3_Status': 'INTEGER', 'G4_Status': 'INTEGER',
        'G5_Status': 'INTEGER', 'G6_Status': 'INTEGER', 'ControllerFW': 'SMALLINT', 'ControllerSync': 'SMALLINT',
        'ControllerStatus': 'SMALLINT', 'ControllerTemp': 'DECIMAL', 'DetectorVoltage': 'SMALLINT', 'DriverVoltage': 'SMALLINT',
        'LedSourceVoltage': 'SMALLINT', 'DoorPosition': 'SMALLINT', 'FanSpeed': 'SMALLINT', 'TapeAdvanceStatus': 'SMALLINT',
        'ChamberStatus': 'SMALLINT', 'ValveStatus': 'SMALLINT', 'PumpStatus': 'CHAR', 'TapeLeftRAW': 'SMALLINT',
        'TapeRightRAW': 'SMALLINT', 'TapePulsesLeft': 'SMALLINT', 'TapePulsesRight': 'SMALLINT', 'FlowCRAW': 'SMALLINT',
        'Flow1RAW': 'SMALLINT', 'FlowRef': 'SMALLINT', 'PumpDriver': 'SMALLINT', 'PumpSpeed': 'SMALLINT',
        'InletHumidity': 'DECIMAL', 'InletTemp': 'DECIMAL', 'DetectorFW': 'SMALLINT', 'DetectorSync': 'SMALLINT',
        'DetectorStatus': 'SMALLINT', 'TapeHumidity': 'DECIMAL', 'TapeTemp': 'DECIMAL', 'ChamberPosition': 'SMALLINT',
        'Ref340': 'INT', 'Sens340_1': 'INT', 'Sens340_2': 'INT', 'Ref370': 'INT',
        'Sens370_1': 'INT', 'Sens370_2': 'INT', 'Ref400': 'INT', 'Sens400_1': 'INT',
        'Sens400_2': 'INT', 'Ref470': 'INT', 'Sens470_1': 'INT', 'Sens470_2': 'INT',
        'Ref520': 'INT', 'Sens520_1': 'INT', 'Sens520_2': 'INT', 'Ref590': 'INT',
        'Sens590_1': 'INT', 'Sens590_2': 'INT', 'Ref630': 'INT', 'Sens630_1': 'INT',
        'Sens630_2': 'INT', 'Ref880': 'INT', 'Sens880_1': 'INT', 'Sens880_2': 'INT',
        'Ref950': 'INT', 'Sens950_1': 'INT', 'Sens950_2': 'INT', 'DetectorStatusCh340': 'SMALLINT',
        'DetectorStatusCh370': 'SMALLINT', 'DetectorStatusCh400': 'SMALLINT', 'DetectorStatusCh470': 'SMALLINT', 'DetectorStatusCh520': 'SMALLINT',
        'DetectorStatusCh590': 'SMALLINT', 'DetectorStatusCh630': 'SMALLINT', 'DetectorStatusCh880': 'SMALLINT', 'DetectorStatusCh950': 'SMALLINT',
        'LedFW': 'SMALLINT', 'LedSync': 'SMALLINT', 'LedStatus': 'SMALLINT', 'LedTemp': 'DECIMAL',
        'LedSourceTemp': 'DECIMAL', 'LedCurrentCh340': 'DECIMAL', 'LedCurrentCh370': 'DECIMAL', 'LedCurrentCh400': 'DECIMAL',
        'LedCurrentCh470': 'DECIMAL', 'LedCurrentCh520': 'DECIMAL', 'LedCurrentCh590': 'DECIMAL', 'LedCurrentCh630': 'DECIMAL',
        'LedCurrentCh880': 'DECIMAL', 'LedCurrentCh950': 'DECIMAL', 'LedStatusCh340': 'SMALLINT', 'LedStatusCh370': 'SMALLINT',
        'LedStatusCh400': 'SMALLINT', 'LedStatusCh470': 'SMALLINT', 'LedStatusCh520': 'SMALLINT', 'LedStatusCh590': 'SMALLINT',
        'LedStatusCh630': 'SMALLINT', 'LedStatusCh880': 'SMALLINT', 'LedStatusCh950': 'SMALLINT', 'Pressure': 'INTEGER',
        'Temp': 'DECIMAL', 'CPU': 'TINYINT', 'DiskSpace': 'INTEGER', 'NumConnections': 'SMALLINT',
    },
    'ExtDeviceData': {
        'ID': 'INTEGER', 'DataID': 'INT', 'DeviceID': 'smallint', 'DevicePort': 'smallint',
        'DeviceData': 'nvarchar (4000)',
    },
    'ExtDeviceSetup': {
        'ID': 'INTEGER', 'Timestamp': 'datetime', 'DataID': 'INTEGER', 'DeviceID1': 'smallint',
        'DeviceID2': 'smallint', 'DeviceID3': 'smallint', 'DeviceID4': 'smallint', 'DeviceID5': 'smallint',
        'DeviceID6': 'smallint',
    },
    'FilterSet': {
        'ID': 'INTEGER', 'FilterSetSN': 'NCHAR (12)', 'Timestamp': 'DATETIME', 'ch370s1f0': 'DECIMAL',
        'ch370s2f0': 'DECIMAL', 'ch470s1f0': 'DECIMAL', 'ch470s2f0': 'DECIMAL', 'ch520s1f0': 'DECIMAL',
        'ch520s2f0': 'DECIMAL', 'ch590s1f0': 'DECIMAL', 'ch590s2f0': 'DECIMAL', 'ch630s1f0': 'DECIMAL',
        'ch630s2f0': 'DECIMAL', 'ch880s1f0': 'DECIMAL', 'ch880s2f0': 'DECIMAL', 'ch950s1f0': 'DECIMAL',
        'ch950s2f0': 'DECIMAL', 'ch370s1f1': 'DECIMAL', 'ch370s2f1': 'DECIMAL', 'ch470s1f1': 'DECIMAL',
        'ch470s2f1': 'DECIMAL', 'ch520s1f1': 'DECIMAL', 'ch520s2f1': 'DECIMAL', 'ch590s1f1': 'DECIMAL',
        'ch590s2f1': 'DECIMAL', 'ch630s1f1': 'DECIMAL', 'ch630s2f1': 'DECIMAL', 'ch880s1f1': 'DECIMAL',
        'ch880s2f1': 'DECIMAL', 'ch950s1f1': 'DECIMAL', 'ch950s2f1': 'DECIMAL', 'ch370s1f2': 'DECIMAL',
        'ch370s2f2': 'DECIMAL', 'ch470s1f2': 'DECIMAL', 'ch470s2f2': 'DECIMAL', 'ch520s1f2': 'DECIMAL',
        'ch520s2f2': 'DECIMAL', 'ch590s1f2': 'DECIMAL', 'ch590s2f2': 'DECIMAL', 'ch630s1f2': 'DECIMAL',
        'ch630s2f2': 'DECIMAL', 'ch880s1f2': 'DECIMAL', 'ch880s2f2': 'DECIMAL', 'ch950s1f2': 'DECIMAL',
        'ch950s2f2': 'DECIMAL', 'ch370s1f3': 'DECIMAL', 'ch370s2f3': 'DECIMAL', 'ch470s1f3': 'DECIMAL',
        'ch470s2f3': 'DECIMAL', 'ch520s1f3': 'DECIMAL', 'ch520s2f3': 'DECIMAL', 'ch590s1f3': 'DECIMAL',
        'ch590s2f3': 'DECIMAL', 'ch630s1f3': 'DECIMAL', 'ch630s2f3': 'DECIMAL', 'ch880s1f3': 'DECIMAL',
        'ch880s2f3': 'DECIMAL', 'ch950s1f3': 'DECIMAL', 'ch950s2f3': 'DECIMAL',
    },
    'Log': {
        'ID': 'INTEGER', 'Timestamp': 'datetime', 'Severity': 'tinyint', 'ClassID': 'smallint',
        'MethodID': 'smallint', 'MessageID': 'smallint', 'Message': 'nvarchar (1024)',
    },
    'Message': {
        'ID': 'INTEGER', 'Message': 'nvarchar(255)',
    },
    'MessageFlawed': {
        'ID': 'INTEGER', 'Timestamp': 'REAL', 'Data': 'TEXT',
    },
    'Method': {
        'ID': 'INTEGER', 'Name': 'nvarchar(500)',
    },
    'NDtest': {
        'ID': 'INTEGER', 'FilterSetSN': 'NCHAR (12)', 'Timestamp': 'DATETIME', 'Reference': 'INTEGER',
        'ch370s1f0': 'DECIMAL', 'ch370s2f0': 'DECIMAL', 'ch470s1f0': 'DECIMAL', 'ch470s2f0': 'DECIMAL',
        'ch520s1f0': 'DECIMAL', 'ch520s2f0': 'DECIMAL', 'ch590s1f0': 'DECIMAL', 'ch590s2f0': 'DECIMAL',
        'ch630s1f0': 'DECIMAL', 'ch630s2f0': 'DECIMAL', 'ch880s1f0': 'DECIMAL', 'ch880s2f0': 'DECIMAL',
        'ch950s1f0': 'DECIMAL', 'ch950s2f0': 'DECIMAL', 'ch370s1f1': 'DECIMAL', 'ch370s2f1': 'DECIMAL',
        'ch470s1f1': 'DECIMAL', 'ch470s2f1': 'DECIMAL', 'ch520s1f1': 'DECIMAL', 'ch520s2f1': 'DECIMAL',
        'ch590s1f1': 'DECIMAL', 'ch590s2f1': 'DECIMAL', 'ch630s1f1': 'DECIMAL', 'ch630s2f1': 'DECIMAL',
        'ch880s1f1': 'DECIMAL', 'ch880s2f1': 'DECIMAL', 'ch950s1f1': 'DECIMAL', 'ch950s2f1': 'DECIMAL',
        'ch370s1f2': 'DECIMAL', 'ch370s2f2': 'DECIMAL', 'ch470s1f2': 'DECIMAL', 'ch470s2f2': 'DECIMAL',
        'ch520s1f2': 'DECIMAL', 'ch520s2f2': 'DECIMAL', 'ch590s1f2': 'DECIMAL', 'ch590s2f2': 'DECIMAL',
        'ch630s1f2': 'DECIMAL', 'ch630s2f2': 'DECIMAL', 'ch880s1f2': 'DECIMAL', 'ch880s2f2': 'DECIMAL',
        'ch950s1f2': 'DECIMAL', 'ch950s2f2': 'DECIMAL', 'ch370s1f3': 'DECIMAL', 'ch370s2f3': 'DECIMAL',
        'ch470s1f3': 'DECIMAL', 'ch470s2f3': 'DECIMAL', 'ch520s1f3': 'DECIMAL', 'ch520s2f3': 'DECIMAL',
        'ch590s1f3': 'DECIMAL', 'ch590s2f3': 'DECIMAL', 'ch630s1f3': 'DECIMAL', 'ch630s2f3': 'DECIMAL',
        'ch880s1f3': 'DECIMAL', 'ch880s2f3': 'DECIMAL', 'ch950s1f3': 'DECIMAL', 'ch950s2f3': 'DECIMAL',
    },
    'ParsedData': {
        'ID': 'INTEGER', 'DataID': 'INTEGER', 'Ames_TRP159_Temp': 'REAL', 'Ames_TRP159_Humidity': 'REAL',
        'Ames_TRP159_Pressure': 'REAL', 'AID_TempIn': 'REAL', 'AID_HumidityIn': 'REAL', 'AID_DewPointIn': 'REAL',
        'AID_TempOut': 'REAL', 'AID_HumidityOut': 'REAL', 'AID_DewPointOut': 'REAL', 'AID_DryingPressure': 'REAL',
        'Gill_GMX300_Temp': 'REAL', 'Gill_GMX300_Humidity': 'REAL', 'Gill_GMX300_Pressure': 'REAL', 'Gill_GMX300_DewPoint': 'REAL',
        'Gill_GMX300_Status': 'REAL', 'Gill_GMX500_Temp': 'REAL', 'Gill_GMX500_Humidity': 'REAL', 'Gill_GMX500_Pressure': 'REAL',
        'Gill_GMX500_DewPoint': 'REAL', 'Gill_GMX500_Speed': 'REAL', 'Gill_GMX500_WindDir': 'REAL', 'Gill_GMX500_CorrectedWindDir': 'REAL',
        'Gill_GMX500_Status': 'REAL',
    },
    'Setup': {
        'ID': 'INTEGER', 'SerialNumber': 'NCHAR', 'Timestamp': 'DATETIME', 'FirmwareVer': 'NVARCHAR',
        'SoftwareVer': 'NVARCHAR', 'NetworkEnabled': 'TINYINT', 'Timebase': 'SMALLINT', 'MAC340': 'DECIMAL',
        'MAC370': 'DECIMAL', 'MAC400': 'DECIMAL', 'MAC470': 'DECIMAL', 'MAC520': 'DECIMAL',
        'MAC590': 'DECIMAL', 'MAC630': 'DECIMAL', 'MAC880': 'DECIMAL', 'MAC950': 'DECIMAL',
        'C': 'DECIMAL', 'Area': 'DECIMAL', 'Zeta': 'DECIMAL', 'ZetaCompensation': 'INTEGER',
        'Aff': 'DECIMAL', 'Abb': 'DECIMAL', 'Abc': 'DECIMAL', 'MacBrC': 'DECIMAL',
        'Pressure': 'INT', 'Temp': 'DECIMAL', 'ATNf1': 'SMALLINT', 'ATNf2': 'SMALLINT',
        'Kmax': 'DECIMAL', 'Kmin': 'DECIMAL', 'Flow': 'SMALLINT', 'FlowRepStd': 'SMALLINT',
        'FlowCa0': 'DECIMAL', 'FlowCa1': 'DECIMAL', 'FlowCa2': 'DECIMAL', 'Flow1a0': 'DECIMAL',
        'Flow1a1': 'DECIMAL', 'Flow1a2': 'DECIMAL', 'TAtype': 'TINYINT', 'TAatnMax': 'SMALLINT',
        'TAinterval': 'TINYINT', 'TAtime': 'DATETIME', 'TapeRighta0': 'DECIMAL', 'TapeRighta1': 'DECIMAL',
        'TapeRighta2': 'DECIMAL', 'TapeRighta3': 'DECIMAL', 'TapeLefta0': 'DECIMAL', 'TapeLefta1': 'DECIMAL',
        'TapeLefta2': 'DECIMAL', 'TapeLefta3': 'DECIMAL', 'WarmUpInterval': 'SMALLINT', 'AutoTestEnabled': 'TINYINT',
        'AutoTestType': 'TINYINT', 'AutoTestDay': 'TINYINT', 'AutoTestTime': 'TIME', 'MeasureTimeStamp': 'TINYINT',
        'HomeInfo': 'INT', 'Display': 'TINYINT', 'DST': 'TINYINT', 'TimeZone': 'NVARCHAR',
        'TapeAdvanceAdjust': 'INT', 'ExternalID': 'TINYINT', 'BHparamID': 'SMALLINT', 'TimeSync': 'TINYINT',
        'DHCP': 'TINYINT', 'InstrumentIP': 'NVARCHAR', 'SubnetMask': 'NVARCHAR', 'Gateway': 'NVARCHAR',
        'dRH_Inlet': 'INT', 'dRH_Tape': 'INT', 'RH_Error': 'TINYINT', 'RH_Warning': 'INT',
        'Average': 'INTEGER', 'AeroBaudRate': 'INTEGER', 'AeroDelimiter': 'INTEGER', 'AdpEnabled': 'INTEGER',
        'RasEnabled': 'INTEGER', 'UidepEnabled': 'INTEGER', 'Language': 'TEXT', 'IndexBClimit0': 'INTEGER',
        'IndexBClimit1': 'INTEGER', 'IndexBClimit2': 'INTEGER', 'IndexBClimit3': 'INTEGER', 'HomeChartPeriod': 'INTEGER',
        'SystemVersion': 'TEXT', 'NTPserver': 'TEXT', 'HighConcAlertLimit': 'INTEGER', 'DNS': 'TEXT',
        'ModbusEnabled': 'INTEGER',
    },
    'TestReports': {
        'ID': 'INTEGER', 'Type': 'smallint', 'Timestamp': 'datetime', 'Passed': 'tinyint',
        'Report': 'nvarchar(4000)',
    },
    'sqlite_sequence': {
        'name': '', 'seq': '',
    },
    'DataView': {
        'ID': 'INTEGER', 'TimestampUTC': 'BIGINT', 'StartTimeUTC': '', 'EndTimeUTC': '',
        'StartTimeLocal': '', 'EndTimeLocal': '', 'SetupID': 'INT', 'SetupTimestamp': '',
        'G0_Status': 'INT', 'G1_Status': 'INT', 'G2_Status': 'INT', 'G3_Status': 'INT',
        'G4_Status': 'INT', 'G5_Status': 'INT', 'G6_Status': 'INT', 'ControllerStatus': 'SMALLINT',
        'DetectorStatus': 'SMALLINT', 'LedStatus': 'SMALLINT', 'ValveStatus': 'SMALLINT', 'PumpStatus': 'SMALLINT',
        'Ref340': 'REAL', 'Sens340_1': 'REAL', 'Sens340_2': 'REAL', 'Ref370': 'REAL',
        'Sens370_1': 'REAL', 'Sens370_2': 'REAL', 'Ref400': 'REAL', 'Sens400_1': 'REAL',
        'Sens400_2': 'REAL', 'Ref470': 'REAL', 'Sens470_1': 'REAL', 'Sens470_2': 'REAL',
        'Ref520': 'REAL', 'Sens520_1': 'REAL', 'Sens520_2': 'REAL', 'Ref590': 'REAL',
        'Sens590_1': 'REAL', 'Sens590_2': 'REAL', 'Ref630': 'REAL', 'Sens630_1': 'REAL',
        'Sens630_2': 'REAL', 'Ref880': 'REAL', 'Sens880_1': 'REAL', 'Sens880_2': 'REAL',
        'Ref950': 'REAL', 'Sens950_1': 'REAL', 'Sens950_2': 'REAL', 'Atn340_1': 'DECIMAL',
        'Atn340_2': 'DECIMAL', 'Atn370_1': 'DECIMAL', 'Atn370_2': 'DECIMAL', 'Atn400_1': 'DECIMAL',
        'Atn400_2': 'DECIMAL', 'Atn470_1': 'DECIMAL', 'Atn470_2': 'DECIMAL', 'Atn520_1': 'DECIMAL',
        'Atn520_2': 'DECIMAL', 'Atn590_1': 'DECIMAL', 'Atn590_2': 'DECIMAL', 'Atn630_1': 'DECIMAL',
        'Atn630_2': 'DECIMAL', 'Atn880_1': 'DECIMAL', 'Atn880_2': 'DECIMAL', 'Atn950_1': 'DECIMAL',
        'Atn950_2': 'DECIMAL', 'BC340_1': 'INT', 'BC340_2': 'INT', 'BC340': 'INT',
        'BC370_1': 'INT', 'BC370_2': 'INT', 'BC370': 'INT', 'BC400_1': 'INT',
        'BC400_2': 'INT', 'BC400': 'INT', 'BC470_1': 'INT', 'BC470_2': 'INT',
        'BC470': 'INT', 'BC520_1': 'INT', 'BC520_2': 'INT', 'BC520': 'INT',
        'BC590_1': 'INT', 'BC590_2': 'INT', 'BC590': 'INT', 'BC630_1': 'INT',
        'BC630_2': 'INT', 'BC630': 'INT', 'BC880_1': 'INT', 'BC880_2': 'INT',
        'BC880': 'INT', 'BC950_1': 'INT', 'BC950_2': 'INT', 'BC950': 'INT',
        'K340': 'DECIMAL', 'K370': 'DECIMAL', 'K400': 'DECIMAL', 'K470': 'DECIMAL',
        'K520': 'DECIMAL', 'K590': 'DECIMAL', 'K630': 'DECIMAL', 'K880': 'DECIMAL',
        'K950': 'DECIMAL', 'BB': 'DECIMAL', 'Babs340': 'DECIMAL', 'Babs370': 'DECIMAL',
        'Babs400': 'DECIMAL', 'Babs470': 'DECIMAL', 'Babs520': 'DECIMAL', 'Babs590': 'DECIMAL',
        'Babs630': 'DECIMAL', 'Babs880': 'DECIMAL', 'Babs950': 'DECIMAL', 'BabsBrC340': 'DECIMAL',
        'BabsBrC370': 'DECIMAL', 'BabsBrC400': 'DECIMAL', 'BabsBrC470': 'DECIMAL', 'BabsBrC520': 'DECIMAL',
        'BabsBrC590': 'DECIMAL', 'BabsBrC630': 'DECIMAL', 'BabsBrC880': 'DECIMAL', 'BabsBrC950': 'DECIMAL',
        'BrC': 'INT', 'Pressure': 'INTEGER', 'Temp': 'DECIMAL', 'Flow1': 'SMALLINT',
        'Flow2': 'SMALLINT', 'FlowC': 'SMALLINT', 'PumpDriver': 'SMALLINT', 'PumpSpeed': 'SMALLINT',
        'ControllerTemp': 'DECIMAL', 'InletHumidity': 'DECIMAL', 'InletTemp': 'DECIMAL', 'TapeHumidity': 'DECIMAL',
        'TapeTemp': 'DECIMAL', 'LedTemp': 'DECIMAL', 'LedSourceTemp': 'SMALLINT', 'TapeAdvanceCount': 'INT',
        'TapeAdvanceLeft': 'SMALLINT', 'CPU': 'TINYINT',
    },
    'DebugView': {
        'ID': 'INTEGER', 'TimestampUTC': '', 'TimestampLocal': '', 'G0_Status': 'INTEGER',
        'G1_Status': 'INTEGER', 'G2_Status': 'INTEGER', 'G3_Status': 'INTEGER', 'G4_Status': 'INTEGER',
        'G5_Status': 'INTEGER', 'G6_Status': 'INTEGER', 'ControllerFW': 'SMALLINT', 'ControllerSync': 'SMALLINT',
        'ControllerStatus': 'SMALLINT', 'ControllerTemp': 'DECIMAL', 'DetectorVoltage': 'SMALLINT', 'DriverVoltage': 'SMALLINT',
        'DoorPosition': 'SMALLINT', 'FanSpeed': 'SMALLINT', 'TapeAdvanceStatus': 'SMALLINT', 'ChamberStatus': 'SMALLINT',
        'ValveStatus': 'SMALLINT', 'PumpStatus': 'CHAR', 'TapeLeftRAW': 'SMALLINT', 'TapeRightRAW': 'SMALLINT',
        'TapePulsesLeft': 'SMALLINT', 'TapePulsesRight': 'SMALLINT', 'FlowCRAW': 'SMALLINT', 'Flow1RAW': 'SMALLINT',
        'FlowRef': 'SMALLINT', 'PumpDriver': 'SMALLINT', 'PumpSpeed': 'SMALLINT', 'InletHumidity': 'DECIMAL',
        'InletTemp': 'DECIMAL', 'DetectorFW': 'SMALLINT', 'DetectorSync': 'SMALLINT', 'DetectorStatus': 'SMALLINT',
        'TapeHumidity': 'DECIMAL', 'TapeTemp': 'DECIMAL', 'ChamberPosition': 'SMALLINT', 'Ref340': 'INT',
        'Sens340_1': 'INT', 'Sens340_2': 'INT', 'Ref370': 'INT', 'Sens370_1': 'INT',
        'Sens370_2': 'INT', 'Ref400': 'INT', 'Sens400_1': 'INT', 'Sens400_2': 'INT',
        'Ref470': 'INT', 'Sens470_1': 'INT', 'Sens470_2': 'INT', 'Ref520': 'INT',
        'Sens520_1': 'INT', 'Sens520_2': 'INT', 'Ref590': 'INT', 'Sens590_1': 'INT',
        'Sens590_2': 'INT', 'Ref630': 'INT', 'Sens630_1': 'INT', 'Sens630_2': 'INT',
        'Ref880': 'INT', 'Sens880_1': 'INT', 'Sens880_2': 'INT', 'Ref950': 'INT',
        'Sens950_1': 'INT', 'Sens950_2': 'INT', 'DetectorStatusCh340': 'SMALLINT', 'DetectorStatusCh370': 'SMALLINT',
        'DetectorStatusCh400': 'SMALLINT', 'DetectorStatusCh470': 'SMALLINT', 'DetectorStatusCh520': 'SMALLINT', 'DetectorStatusCh590': 'SMALLINT',
        'DetectorStatusCh630': 'SMALLINT', 'DetectorStatusCh880': 'SMALLINT', 'DetectorStatusCh950': 'SMALLINT', 'LedFW': 'SMALLINT',
        'LedSync': 'SMALLINT', 'LedStatus': 'SMALLINT', 'LedTemp': 'DECIMAL', 'LedSourceTemp': 'DECIMAL',
        'LedCurrentCh340': 'DECIMAL', 'LedCurrentCh370': 'DECIMAL', 'LedCurrentCh400': 'DECIMAL', 'LedCurrentCh470': 'DECIMAL',
        'LedCurrentCh520': 'DECIMAL', 'LedCurrentCh590': 'DECIMAL', 'LedCurrentCh630': 'DECIMAL', 'LedCurrentCh880': 'DECIMAL',
        'LedCurrentCh950': 'DECIMAL', 'LedStatusCh340': 'SMALLINT', 'LedStatusCh370': 'SMALLINT', 'LedStatusCh400': 'SMALLINT',
        'LedStatusCh470': 'SMALLINT', 'LedStatusCh520': 'SMALLINT', 'LedStatusCh590': 'SMALLINT', 'LedStatusCh630': 'SMALLINT',
        'LedStatusCh880': 'SMALLINT', 'LedStatusCh950': 'SMALLINT', 'Pressure': 'INTEGER', 'Temp': 'DECIMAL',
        'CPU': 'TINYINT', 'DiskSpace': 'INTEGER', 'NumConnections': 'SMALLINT',
    },
    'LogView': {
        'ID': 'INTEGER', 'Timestamp': 'datetime', 'ClassName': 'nvarchar(100)', 'Method': 'nvarchar(500)',
        'Message': '',
    },
}

COLUMNS_TCA08 = {
    'Data': {
        'ID': 'INTEGER', 'TimeStamp': 'DATETIME', 'SetupID': 'INTEGER', 'Timebase': 'INTEGER',
        'G0_Status': 'INTEGER', 'G1_Status': 'INTEGER', 'G2_Status': 'INTEGER', 'G3_Status': 'INTEGER',
        'G4_Status': 'INTEGER', 'G5_Status': 'INTEGER', 'G6_Status': 'INTEGER', 'Ch1_Status': 'STRING',
        'Ch1_SampleID': 'INTEGER', 'Ch2_Status': 'STRING', 'Ch2_SampleID': 'INTEGER', 'MainBoardStatus': 'CHAR',
        'Ch1BoardStatus': 'CHAR', 'Ch2BoardStatus': 'CHAR', 'SensorBoardStatus': 'CHAR', 'FlowS': 'DECIMAL',
        'setFlowS': 'DECIMAL', 'FlowS_RAW': 'INTEGER', 'SamplePumpSpeed': 'INTEGER', 'FlowA': 'DECIMAL',
        'setFlowA': 'DECIMAL', 'FlowA_RAW': 'INTEGER', 'AnalyticPumpSpeed': 'INTEGER', 'Solenoid1': 'INTEGER',
        'Solenoid2': 'INTEGER', 'Solenoid5': 'INTEGER', 'BallValve1': 'CHAR', 'BallValve2': 'CHAR',
        'BallValve3': 'CHAR', 'BallValve4': 'CHAR', 'Ch1_Temp': 'INTEGER', 'Ch2_Temp': 'INTEGER',
        'Ch1_Voltage1': 'DECIMAL', 'setCh1Voltage1': 'DECIMAL', 'Ch1_Current1': 'DECIMAL', 'Ch1_Voltage2': 'DECIMAL',
        'setCh1Voltage2': 'DECIMAL', 'Ch1_Current2': 'DECIMAL', 'Ch2_Voltage1': 'DECIMAL', 'setCh2Voltage1': 'DECIMAL',
        'Ch2_Current1': 'DECIMAL', 'Ch2_Voltage2': 'DECIMAL', 'setCh2Voltage2': 'DECIMAL', 'Ch2_Current2': 'DECIMAL',
        'Ch1_SafetyTemp': 'INTEGER', 'Ch2_SafetyTemp': 'INTEGER', 'SafetyTempInt': 'INTEGER', 'Fan1': 'INTEGER',
        'Fan2': 'INTEGER', 'Fan3': 'INTEGER', 'Fan4': 'INTEGER', 'LicorTemp': 'DECIMAL',
        'LicorPressure': 'DECIMAL', 'LicorCO2': 'DECIMAL', 'LicorCO2abs': 'DECIMAL', 'LicorH2O': 'DECIMAL',
        'LicorH2Oabs': 'DECIMAL', 'LicorH2Odewpoint': 'DECIMAL', 'LicorVoltage': 'DECIMAL', 'CPU': 'DECIMAL',
        'RAM': 'INTEGER', 'CPU_TEMP': 'DECIMAL',
    },
    'DatabaseVer': {
        'ID': 'INTEGER', 'TimeStamp': 'DATETIME', 'Version': 'STRING',
    },
    'DateOrder': {
        'ID': 'INTEGER', 'Date': 'DATETIME', 'FirstID': 'INTEGER', 'LastID': 'INTEGER',
    },
    'ExtDeviceData': {
        'ID': 'INTEGER', 'DataID': 'INTEGER', 'DeviceID': 'INTEGER', 'DeviceData': 'STRING',
    },
    'ExtDeviceSetup': {
        'ID': 'INTEGER', 'DataID': 'INTEGER', 'DeviceID1': 'INTEGER', 'DeviceID2': 'INTEGER',
        'DeviceID3': 'INTEGER', 'DeviceID4': 'INTEGER', 'DeviceID5': 'INTEGER', 'DeviceID6': 'INTEGER',
    },
    'FilterIntegrity': {
        'ID': 'INTEGER', 'SampleID': 'INTEGER', 'Chamber': 'INTEGER', 'p1': 'DECIMAL',
        'p2': 'DECIMAL', 'dp': 'DECIMAL',
    },
    'HeaterResistance': {
        'ID': 'INTEGER', 'TimeStamp': 'DATETIME', 'SampleID': 'INTEGER', 'R_Ch1_1': 'DECIMAL',
        'R_Ch1_2': 'DECIMAL', 'R_Ch2_1': 'DECIMAL', 'R_Ch2_2': 'DECIMAL', 'U11': 'INTEGER',
        'U12': 'INTEGER', 'U13': 'INTEGER', 'U21': 'INTEGER', 'U22': 'INTEGER',
        'U23': 'INTEGER',
    },
    'Log': {
        'ID': 'INTEGER', 'TimeStamp': 'DATETIME', 'Severity': 'INTEGER', 'MessageID': 'INTEGER',
        'Message': 'STRING',
    },
    'OfflineResult': {
        'ID': 'INTEGER', 'SampleID': 'INTEGER', 'SampleName': 'STRING', 'StartTimeUTC': 'DATETIME',
        'StartTimeLocal': 'DATETIME', 'TCcounts': 'DECIMAL', 'TCmass': 'DECIMAL', 'TCconc': 'DECIMAL',
        'PunchArea': 'DECIMAL', 'DryingTime': 'INTEGER', 'Chamber': 'INTEGER', 'SetupID': 'INTEGER',
        'a1': 'DECIMAL', 'b1': 'DECIMAL', 'c1': 'DECIMAL', 'd1': 'DECIMAL',
        'e1': 'DECIMAL', 'f1': 'DECIMAL', 'a2': 'DECIMAL', 'b2': 'DECIMAL',
        'c2': 'DECIMAL', 'd2': 'DECIMAL', 'e2': 'DECIMAL', 'f2': 'DECIMAL',
    },
    'OnlineResult': {
        'ID': 'INTEGER', 'SampleID': 'INTEGER', 'StartTimeUTC': 'DATETIME', 'EndTimeUTC': 'DATETIME',
        'StartTimeLocal': 'DATETIME', 'EndTimeLocal': 'DATETIME', 'TCcounts': 'DECIMAL', 'TCmass': 'DECIMAL',
        'TCconc': 'DECIMAL', 'AE33_BC6': 'INTEGER', 'AE33_ValidData': 'DECIMAL', 'AE33_b': 'DECIMAL',
        'OC': 'DECIMAL', 'EC': 'DECIMAL', 'CO2': 'DECIMAL', 'Volume': 'DECIMAL',
        'Chamber': 'INTEGER', 'SetupID': 'INTEGER', 'a1': 'DECIMAL', 'b1': 'DECIMAL',
        'c1': 'DECIMAL', 'd1': 'DECIMAL', 'e1': 'DECIMAL', 'f1': 'DECIMAL',
        'a2': 'DECIMAL', 'b2': 'DECIMAL', 'c2': 'DECIMAL', 'd2': 'DECIMAL',
        'e2': 'DECIMAL', 'f2': 'DECIMAL',
    },
    'SamplerData': {
        'ID': 'INTEGER', 'Timestamp': 'datetime', 'SampleID': 'INTEGER', 'SamplerSetFlow': 'INTEGER',
        'SamplerFlow': 'INTEGER',
    },
    'SamplerResults': {
        'ID': 'INTEGER', 'SampleID': 'INTEGER', 'SampleName': 'TEXT', 'StartTime': 'datetime',
        'EndTime': 'datetime', 'TCA08conc': 'INTEGER', 'AverageFlow': 'decimal',
    },
    'Setup': {
        'ID': 'INTEGER', 'TimeStamp': 'datetime', 'SerialNumber': 'TEXT', 'SetFlowS': 'decimal',
        'SetFlowA': 'decimal', 'Area': 'decimal', 'FlowFormulaA': 'decimal', 'FlowFormulaB': 'decimal',
        'FlowFormulaC': 'decimal', 'FlowFormulaD': 'decimal', 'FlowFormulaE': 'decimal', 'FlowFormulaF': 'decimal',
        'CCch1': 'decimal', 'CCch2': 'decimal', 'SlopeTempCh1': 'decimal', 'InterceptTempCh1': 'decimal',
        'SlopeTempCh2': 'decimal', 'InterceptTempCh2': 'decimal', 'SampleTime': 'INTEGER', 'C0': 'INTEGER',
        'C1': 'INTEGER', 'C2': 'INTEGER', 'C3': 'INTEGER', 'C4': 'INTEGER',
        'C5': 'INTEGER', 'C6': 'INTEGER', 'C7': 'INTEGER', 'C8': 'INTEGER',
        'C9': 'INTEGER', 'C10': 'INTEGER', 'P11': 'INTEGER', 'P12': 'INTEGER',
        'P13': 'INTEGER', 'P21': 'INTEGER', 'P22': 'INTEGER', 'P23': 'INTEGER',
        'A0': 'INTEGER', 'A2': 'INTEGER', 'A3': 'INTEGER', 'FlowRepStd': 'INTEGER',
        'Temp': 'decimal', 'Pressure': 'decimal', 'SoftwareVersion': 'TEXT', 'FirmwareVersion': 'INTEGER',
        'AE33_b': 'decimal', 'TimeZone': 'TEXT', 'DST': 'INTEGER', 'TimeProtocol': 'INTEGER',
        'BHparamID': 'INTEGER', 'FilterIntegrity_threshold': 'decimal', 'DHCP': 'INTEGER', 'InstrumentIP': 'TEXT',
        'SubnetMask': 'TEXT', 'Gateway': 'TEXT', 'BHBaudRate': 'INTEGER', 'ModBusID': 'INTEGER',
        'ModBusBaudRate': 'INTEGER', 'AeroBaudRate': 'INTEGER', 'AeroDelimiter': 'INTEGER', 'AdpEnabled': 'INTEGER',
        'UidepEnabled': 'INTEGER', 'RasEnabled': 'INTEGER',
    },
    'TestReports': {
        'ID': 'INTEGER', 'TimeStamp': 'datetime', 'ReportType': 'INTEGER', 'Passed': 'INTEGER',
        'Report': 'TEXT',
    },
    'sqlite_sequence': {
        'name': '', 'seq': '',
    },
}

COLUMNS_TCA09 = {
    'Data': {
        'ID': 'INTEGER', 'SampleID': 'INTEGER', 'SampleStartTimeUTC': 'INTEGER', 'SampleStartTimeLocal': 'INTEGER',
        'SampleEndTimeUTC': 'INTEGER', 'SampleEndTimeLocal': 'INTEGER', 'AnalysisStartTimeUTC': 'INTEGER', 'AnalysisStartTimeLocal': 'INTEGER',
        'AnalysisEndTimeUTC': 'INTEGER', 'AnalysisEndTimeLocal': 'INTEGER', 'SetupID': 'INTEGER', 'SettingsID': 'INTEGER',
        'SampleName': 'varchar', 'PunchArea': 'float', 'DryingTime': 'INTEGER', 'G0_Status': 'INTEGER',
        'G1_Status': 'INTEGER', 'G2_Status': 'INTEGER', 'G3_Status': 'INTEGER', 'G4_Status': 'INTEGER',
        'G5_Status': 'INTEGER', 'G6_Status': 'INTEGER', 'G7_Status': 'INTEGER', 'Chamber': 'INTEGER',
        'FilterIntegrity': 'INTEGER', 'TC_Counts': 'float', 'Zero_Counts': 'float', 'TCmass': 'INTEGER',
        'TCconc_surface': 'INTEGER', 'TCconc_volume': 'INTEGER', 'SampleFlow': 'float', 'AnalyticFlow': 'float',
        'Volume': 'float', 'Pressure': 'float', 'Temp': 'float', 'BC880': 'INTEGER',
        'BB': 'float', 'POC': 'float', 'SOC': 'float', 'BC_ValidData': 'float',
        'b': 'float', 'OC': 'float', 'EC': 'float', 'CO2': 'float',
        'NDIR_Temp': 'float', 'NDIR_Pressure': 'float', 'NDIR_CO2': 'float', 'NDIR_CO2abs': 'float',
        'NDIR_H2O': 'float', 'NDIR_H2Oabs': 'float', 'NDIR_H2Odewpoint': 'float', 'NDIR_Voltage': 'float',
        'SamplePumpDriver': 'INTEGER', 'AnalyticPumpDriver': 'INTEGER', 'SamplePumpSpeed': 'INTEGER', 'AnalyticPumpSpeed': 'INTEGER',
        'Ch1MaxTemp': 'INTEGER', 'Ch2MaxTemp': 'INTEGER', 'InternalTemp': 'INTEGER', 'CPU': 'INTEGER',
        'DBsize': 'INTEGER', 'NumConnections': 'INTEGER', 'PolyA0': 'float', 'PolyA1': 'float',
        'PolyA2': 'float', 'PolyA3': 'float', 'PolyA4': 'float', 'PolyA5': 'float',
        'PolyB0': 'float', 'PolyB1': 'float', 'PolyB2': 'float', 'PolyB3': 'float',
        'PolyB4': 'float', 'PolyB5': 'float', 'TCconc_volume_CleanAir': 'INTEGER', 'AnalysisType': 'INTEGER',
        'BCff': 'float', 'BCbb': 'float', 'POCff': 'float', 'POCbb': 'float',
        'ECff': 'float', 'ECbb': 'float',
    },
    'DatabaseVer': {
        'ID': 'INTEGER', 'TimestampLocal': 'INTEGER', 'Version': 'STRING',
    },
    'DateOrder': {
        'ID': 'INTEGER', 'Date': 'DATETIME', 'FirstID': 'INTEGER', 'LastID': 'INTEGER',
    },
    'DebugData': {
        'ID': 'INTEGER', 'TimestampUTC': 'INTEGER', 'TimestampLocal': 'INTEGER', 'SetupID': 'INTEGER',
        'SettingsID': 'INTEGER', 'G0_Status': 'INTEGER', 'G1_Status': 'INTEGER', 'G2_Status': 'INTEGER',
        'G3_Status': 'INTEGER', 'G4_Status': 'INTEGER', 'G5_Status': 'INTEGER', 'G6_Status': 'INTEGER',
        'G7_Status': 'INTEGER', 'Ch1_Analysis': 'varchar', 'Ch1_Status': 'varchar', 'Ch1_SampleID': 'INTEGER',
        'Ch2_Status': 'varchar', 'Ch2_Analysis': 'varchar', 'Ch2_SampleID': 'INTEGER', 'Ack': 'varchar',
        'ReturnHeartbeat': 'INTEGER', 'Heartbeat': 'INTEGER', 'FW_Status': 'INTEGER', 'FW_LicorStatus': 'INTEGER',
        'FW_ErrorStatus': 'INTEGER', 'Beeper': 'INTEGER', 'AnalyticPumpFlow': 'float', 'AnalyticPumpSet': 'INTEGER',
        'AnalyticPumpFlowRAW': 'INTEGER', 'AnalyticPumpSpeed': 'INTEGER', 'AnalyticPumpDriver': 'INTEGER', 'SamplePumpFlow': 'float',
        'SamplePumpSet': 'INTEGER', 'SamplePumpFlowRAW': 'INTEGER', 'SamplePumpSpeed': 'INTEGER', 'SamplePumpDriver': 'INTEGER',
        'SamplePumpStatus': 'INTEGER', 'Pressure': 'float', 'Temp': 'float', 'SV12': 'INTEGER',
        'SV22': 'INTEGER', 'SV30': 'INTEGER', 'SV31': 'INTEGER', 'SV32': 'INTEGER',
        'SV33': 'INTEGER', 'BV11': 'INTEGER', 'BV21': 'INTEGER', 'BV31': 'INTEGER',
        'SelectedChamber': 'INTEGER', 'Heater1SetPWM': 'INTEGER', 'Heater1Voltage': 'float', 'Heater1Current': 'float',
        'Heater1Driver': 'INTEGER', 'Heater1Status': 'INTEGER', 'Heater1Error': 'INTEGER', 'Heater2SetPWM': 'INTEGER',
        'Heater2Voltage': 'float', 'Heater2Current': 'float', 'Heater2Driver': 'INTEGER', 'Heater2Status': 'INTEGER',
        'Heater2Error': 'INTEGER', 'Ch1Temp': 'INTEGER', 'Ch2Temp': 'INTEGER', 'PowerBoardTemp1': 'INTEGER',
        'PowerBoardTemp2': 'INTEGER', 'PCB_Ch1Temp': 'INTEGER', 'PCB_Ch2Temp': 'INTEGER', 'NTC_Ch1Temp': 'INTEGER',
        'NTC_Ch2Temp': 'INTEGER', 'LockStatus': 'INTEGER', 'SetFan1': 'INTEGER', 'Fan1': 'INTEGER',
        'SetFan2': 'INTEGER', 'Fan2': 'INTEGER', 'SetFan3': 'INTEGER', 'Fan3': 'INTEGER',
        'NDIR_Temp': 'float', 'NDIR_Pressure': 'float', 'NDIR_CO2': 'float', 'NDIR_CO2abs': 'float',
        'NDIR_H2O': 'float', 'NDIR_H2Oabs': 'float', 'NDIR_H2Odewpoint': 'float', 'CPU': 'INTEGER',
        'RAM': 'INTEGER', 'CPU_Temp': 'INTEGER', 'DBsize': 'INTEGER', 'NumConnections': 'INTEGER',
        'Reserved1': 'INTEGER', 'Reserved2': 'INTEGER', 'Reserved3': 'INTEGER', 'Reserved4': 'INTEGER',
        'Reserved5': 'INTEGER', 'Reserved6': 'INTEGER', 'Reserved7': 'INTEGER', 'Reserved8': 'INTEGER',
        'Reserved9': 'INTEGER',
    },
    'ExtDeviceAvgData': {
        'ID': 'INTEGER', 'DataID': 'INTEGER', 'SampleID': 'INTEGER', 'SampleStartTimeUTC': 'INTEGER',
        'SampleStartTimeLocal': 'INTEGER', 'SampleEndTimeUTC': 'INTEGER', 'SampleEndTimeLocal': 'INTEGER', 'DeviceID': 'INTEGER',
        'Validity': 'INTEGER', 'DeviceData': 'TEXT',
    },
    'ExtDeviceData': {
        'ID': 'INTEGER', 'TimestampLocal': 'INTEGER', 'DebugDataID': 'INTEGER', 'DeviceID': 'INTEGER',
        'DeviceData': 'STRING',
    },
    'ExtDeviceSetup': {
        'ID': 'INTEGER', 'TimestampLocal': 'INTEGER', 'DebugDataID': 'INTEGER', 'DeviceID1': 'INTEGER',
        'DeviceID2': 'INTEGER', 'DeviceID3': 'INTEGER',
    },
    'HeaterResistance': {
        'ID': 'INTEGER', 'TimestampLocal': 'INTEGER', 'SampleID': 'INTEGER', 'R_Ch1_1': 'DECIMAL',
        'R_Ch1_2': 'DECIMAL', 'R_Ch2_1': 'DECIMAL', 'R_Ch2_2': 'DECIMAL', 'U11': 'INTEGER',
        'U12': 'INTEGER', 'U13': 'INTEGER', 'U21': 'INTEGER', 'U22': 'INTEGER',
        'U23': 'INTEGER',
    },
    'Log': {
        'ID': 'INTEGER', 'TimestampLocal': 'INTEGER', 'Severity': 'INTEGER', 'MessageID': 'INTEGER',
        'Message': 'STRING',
    },
    'MaintenanceData': {
        'ID': 'INTEGER', 'TimestampUTC': 'INTEGER', 'MaintenanceID': 'INTEGER', 'Value': 'INTEGER',
    },
    'Settings': {
        'ID': 'INTEGER', 'SerialNumber': 'TEXT', 'TimestampLocal': 'INTEGER', 'Language': 'TEXT',
        'DHCP': 'INTEGER', 'InstrumentIP': 'TEXT', 'SubnetMask': 'TEXT', 'Gateway': 'TEXT',
        'DNS': 'TEXT', 'HomeChartPeriod': 'INTEGER', 'RasEnabled': 'INTEGER', 'AdpEnabled': 'INTEGER',
        'AeroBaudRate': 'INTEGER', 'AeroDelimiter': 'INTEGER', 'UidepEnabled': 'INTEGER', 'BHparamID': 'INTEGER',
        'BHBaudRate': 'INTEGER', 'ModBusID': 'INTEGER', 'ModBusBaudRate': 'INTEGER', 'Display': 'INTEGER',
        'HomeChartData': 'INTEGER', 'ModBusEnabled': 'INTEGER',
    },
    'Setup': {
        'ID': 'INTEGER', 'SerialNumber': 'TEXT', 'TimestampLocal': 'INTEGER', 'FirmwareVersion': 'TEXT',
        'SoftwareVersion': 'TEXT', 'SystemVersion': 'TEXT', 'Timebase': 'INTEGER', 'Area': 'REAL',
        'SetFlowS': 'REAL', 'SetFlowA': 'REAL', 'FlowSa0': 'REAL', 'FlowSa1': 'REAL',
        'FlowSa2': 'REAL', 'FlowAa0': 'REAL', 'FlowAa1': 'REAL', 'FlowAa2': 'REAL',
        'CCch1': 'REAL', 'CCch2': 'REAL', 'SlopeTempCh1': 'REAL', 'InterceptTempCh1': 'REAL',
        'SlopeTempCh2': 'REAL', 'InterceptTempCh2': 'REAL', 'C0': 'INTEGER', 'C1': 'INTEGER',
        'C2': 'INTEGER', 'C3': 'INTEGER', 'C4': 'INTEGER', 'C5': 'INTEGER',
        'C6': 'INTEGER', 'P11': 'INTEGER', 'P12': 'INTEGER', 'P13': 'INTEGER',
        'P21': 'INTEGER', 'P22': 'INTEGER', 'P23': 'INTEGER', 'PS1a0': 'REAL',
        'PS1a1': 'REAL', 'PS1a2': 'REAL', 'PS1a3': 'REAL', 'PS2a0': 'REAL',
        'PS2a1': 'REAL', 'PS2a2': 'REAL', 'PS2a3': 'REAL', 'A0': 'INTEGER',
        'A2': 'INTEGER', 'A3': 'INTEGER', 'FlowRepStd': 'INTEGER', 'Pressure': 'REAL',
        'Temp': 'REAL', 'CleanAirTestEnabled': 'INTEGER', 'CleanAirTestType': 'INTEGER', 'CleanAirTestDay': 'INTEGER',
        'CleanAirTestTime': 'INTEGER', 'CleanAirLimit': 'INTEGER', 'b': 'REAL', 'DST': 'INTEGER',
        'TimeZone': 'TEXT', 'TimeSync': 'INTEGER', 'FilterIntegrityThreshold': 'REAL', 'NTPserver': 'TEXT',
        'CleanChambers': 'INTEGER', 'HeaterSavingMode': 'INTEGER', 'HeaterSavingModeCount': 'INTEGER', 'NDIRSerialNumber': 'varchar',
        'OC_BC_PrimaryRatio_ff': 'float', 'OC_BC_PrimaryRatio_bb': 'float', 'LeakageTest': 'INTEGER',
    },
    'TestReports': {
        'ID': 'INTEGER', 'TimestampLocal': 'INTEGER', 'Type': 'SMALLINT', 'Passed': 'TINYINT',
        'Report': 'NVARCHAR (4000)',
    },
    'sqlite_sequence': {
        'name': '', 'seq': '',
    },
    'DataView': {
        'ID': 'INTEGER', 'SampleID': 'INTEGER', 'SampleStartTimeUTC': '', 'SampleStartTimeLocal': '',
        'SampleEndTimeUTC': '', 'SampleEndTimeLocal': '', 'AnalysisStartTimeUTC': '', 'AnalysisStartTimeLocal': '',
        'AnalysisEndTimeUTC': '', 'AnalysisEndTimeLocal': '', 'TCconc_volume': 'INTEGER', 'TCconc_volume_CleanAir': 'INTEGER',
        'G0_Status': 'INTEGER', 'G1_Status': 'INTEGER', 'G2_Status': 'INTEGER', 'G3_Status': 'INTEGER',
        'G4_Status': 'INTEGER', 'G5_Status': 'INTEGER', 'G6_Status': 'INTEGER', 'G7_Status': 'INTEGER',
        'AnalysisType': 'INTEGER', 'BC880': 'INTEGER', 'BC_ValidData': 'float', 'BB': 'float',
        'BCff': 'float', 'BCbb': 'float', 'b': 'float', 'OC': 'float',
        'EC': 'float', 'ECff': 'float', 'ECbb': 'float', 'POC': 'float',
        'POCff': 'float', 'POCbb': 'float', 'SOC': 'float', 'SampleName': 'varchar',
        'TCconc_surface': 'INTEGER', 'PunchArea': 'float', 'TCmass': 'INTEGER', 'DryingTime': 'INTEGER',
        'TC_Counts': 'float', 'Zero_Counts': 'float', 'Chamber': 'INTEGER', 'FilterIntegrity': 'INTEGER',
        'SampleFlow': 'float', 'AnalyticFlow': 'float', 'Volume': 'float', 'Pressure': 'float',
        'Temp': 'float', 'SetupID': 'INTEGER', 'SettingsID': 'INTEGER', 'CO2': 'float',
        'NDIR_Temp': 'float', 'NDIR_Pressure': 'float', 'NDIR_CO2': 'float', 'NDIR_CO2abs': 'float',
        'NDIR_H2O': 'float', 'NDIR_H2Oabs': 'float', 'NDIR_H2Odewpoint': 'float', 'NDIR_Voltage': 'float',
        'SamplePumpDriver': 'INTEGER', 'AnalyticPumpDriver': 'INTEGER', 'SamplePumpSpeed': 'INTEGER', 'AnalyticPumpSpeed': 'INTEGER',
        'Ch1MaxTemp': 'INTEGER', 'Ch2MaxTemp': 'INTEGER', 'InternalTemp': 'INTEGER', 'CPU': 'INTEGER',
        'DBsize': 'INTEGER', 'NumConnections': 'INTEGER', 'PolyA0': 'float', 'PolyA1': 'float',
        'PolyA2': 'float', 'PolyA3': 'float', 'PolyA4': 'float', 'PolyA5': 'float',
        'PolyB0': 'float', 'PolyB1': 'float', 'PolyB2': 'float', 'PolyB3': 'float',
        'PolyB4': 'float', 'PolyB5': 'float',
    },
    'DatabaseVerView': {
        'ID': 'INTEGER', 'TimestampLocal': '', 'Version': 'STRING',
    },
    'DebugDataView': {
        'ID': 'INTEGER', 'TimestampUTC': '', 'TimestampLocal': '', 'SetupID': 'INTEGER',
        'SettingsID': 'INTEGER', 'G0_Status': 'INTEGER', 'G1_Status': 'INTEGER', 'G2_Status': 'INTEGER',
        'G3_Status': 'INTEGER', 'G4_Status': 'INTEGER', 'G5_Status': 'INTEGER', 'G6_Status': 'INTEGER',
        'G7_Status': 'INTEGER', 'Ch1_Analysis': 'varchar', 'Ch1_Status': 'varchar', 'Ch1_SampleID': 'INTEGER',
        'Ch2_Status': 'varchar', 'Ch2_Analysis': 'varchar', 'Ch2_SampleID': 'INTEGER', 'Ack': 'varchar',
        'ReturnHeartbeat': 'INTEGER', 'Heartbeat': 'INTEGER', 'FW_Status': 'INTEGER', 'FW_LicorStatus': 'INTEGER',
        'FW_ErrorStatus': 'INTEGER', 'Beeper': 'INTEGER', 'AnalyticPumpFlow': 'float', 'AnalyticPumpSet': 'INTEGER',
        'AnalyticPumpFlowRAW': 'INTEGER', 'AnalyticPumpSpeed': 'INTEGER', 'AnalyticPumpDriver': 'INTEGER', 'SamplePumpFlow': 'float',
        'SamplePumpSet': 'INTEGER', 'SamplePumpFlowRAW': 'INTEGER', 'SamplePumpSpeed': 'INTEGER', 'SamplePumpDriver': 'INTEGER',
        'SamplePumpStatus': 'INTEGER', 'Pressure': 'float', 'Temp': 'float', 'SV12': 'INTEGER',
        'SV22': 'INTEGER', 'SV30': 'INTEGER', 'SV31': 'INTEGER', 'SV32': 'INTEGER',
        'SV33': 'INTEGER', 'BV11': 'INTEGER', 'BV21': 'INTEGER', 'BV31': 'INTEGER',
        'SelectedChamber': 'INTEGER', 'Heater1SetPWM': 'INTEGER', 'Heater1Voltage': 'float', 'Heater1Current': 'float',
        'Heater1Driver': 'INTEGER', 'Heater1Status': 'INTEGER', 'Heater1Error': 'INTEGER', 'Heater2Voltage': 'float',
        'Heater2SetPWM': 'INTEGER', 'Heater2Current': 'float', 'Heater2Driver': 'INTEGER', 'Heater2Status': 'INTEGER',
        'Heater2Error': 'INTEGER', 'Ch1Temp': 'INTEGER', 'Ch2Temp': 'INTEGER', 'PCB_Ch1Temp': 'INTEGER',
        'PCB_Ch2Temp': 'INTEGER', 'NTC_Ch1Temp': 'INTEGER', 'NTC_Ch2Temp': 'INTEGER', 'PowerBoardTemp1': 'INTEGER',
        'PowerBoardTemp2': 'INTEGER', 'LockStatus': 'INTEGER', 'SetFan1': 'INTEGER', 'Fan1': 'INTEGER',
        'SetFan2': 'INTEGER', 'Fan2': 'INTEGER', 'SetFan3': 'INTEGER', 'Fan3': 'INTEGER',
        'NDIR_Temp': 'float', 'NDIR_Pressure': 'float', 'NDIR_CO2': 'float', 'NDIR_CO2abs': 'float',
        'NDIR_H2O': 'float', 'NDIR_H2Oabs': 'float', 'NDIR_H2Odewpoint': 'float', 'CPU': 'INTEGER',
        'RAM': 'INTEGER', 'CPU_Temp': 'INTEGER', 'DBsize': 'INTEGER', 'NumConnections': 'INTEGER',
        'Reserved1': 'INTEGER', 'Reserved2': 'INTEGER', 'Reserved3': 'INTEGER', 'Reserved4': 'INTEGER',
        'Reserved5': 'INTEGER', 'Reserved6': 'INTEGER', 'Reserved7': 'INTEGER', 'Reserved8': 'INTEGER',
        'Reserved9': 'INTEGER',
    },
    'ExtDeviceAvgDataView': {
        'ID': 'INTEGER', 'DataID': 'INTEGER', 'SampleID': 'INTEGER', 'SampleStartTimeUTC': '',
        'SampleStartTimeLocal': '', 'SampleEndTimeUTC': '', 'SampleEndTimeLocal': '', 'DeviceID': 'INTEGER',
        'Validity': 'INTEGER', 'DeviceData': 'TEXT',
    },
    'ExtDeviceDataView': {
        'ID': 'INTEGER', 'TimestampLocal': '', 'DebugDataID': 'INTEGER', 'DeviceID': 'INTEGER',
        'DeviceData': 'STRING',
    },
    'ExtDeviceSetupView': {
        'ID': 'INTEGER', 'TimestampLocal': '', 'DebugDataID': 'INTEGER', 'DeviceID1': 'INTEGER',
        'DeviceID2': 'INTEGER', 'DeviceID3': 'INTEGER',
    },
    'HeaterResistanceView': {
        'ID': 'INTEGER', 'TimestampLocal': '', 'SampleID': 'INTEGER', 'R_Ch1_1': 'DECIMAL',
        'R_Ch1_2': 'DECIMAL', 'R_Ch2_1': 'DECIMAL', 'R_Ch2_2': 'DECIMAL', 'U11': 'INTEGER',
        'U12': 'INTEGER', 'U13': 'INTEGER', 'U21': 'INTEGER', 'U22': 'INTEGER',
        'U23': 'INTEGER',
    },
    'LogView': {
        'ID': 'INTEGER', 'TimestampLocal': '', 'Severity': 'INTEGER', 'MessageID': 'INTEGER',
        'Message': 'STRING',
    },
    'MaintenanceDataView': {
        'ID': 'INTEGER', 'TimestampUTC': '', 'MaintenanceID': 'INTEGER', 'Description': '',
        'Value': 'INTEGER',
    },
    'OfflineDataView': {
        'ID': 'INTEGER', 'SampleID': 'INTEGER', 'AnalysisStartTimeUTC': '', 'AnalysisStartTimeLocal': '',
        'AnalysisEndTimeUTC': '', 'AnalysisEndTimeLocal': '', 'G0_Status': 'INTEGER', 'G1_Status': 'INTEGER',
        'G2_Status': 'INTEGER', 'G3_Status': 'INTEGER', 'G4_Status': 'INTEGER', 'G5_Status': 'INTEGER',
        'G6_Status': 'INTEGER', 'G7_Status': 'INTEGER', 'SampleName': 'varchar', 'TCconc_surface': 'INTEGER',
        'PunchArea': 'float', 'TCmass': 'INTEGER', 'DryingTime': 'INTEGER', 'TC_Counts': 'float',
        'Zero_Counts': 'float', 'Chamber': 'INTEGER', 'FilterIntegrity': 'INTEGER', 'AnalyticFlow': 'float',
        'SetupID': 'INTEGER', 'SettingsID': 'INTEGER', 'CO2': 'float',
    },
    'OnlineDataView': {
        'ID': 'INTEGER', 'SampleID': 'INTEGER', 'SampleStartTimeUTC': '', 'SampleStartTimeLocal': '',
        'SampleEndTimeUTC': '', 'SampleEndTimeLocal': '', 'AnalysisStartTimeUTC': '', 'AnalysisStartTimeLocal': '',
        'AnalysisEndTimeUTC': '', 'AnalysisEndTimeLocal': '', 'TCconc_volume': 'INTEGER', 'TCconc_volume_CleanAir': 'INTEGER',
        'G0_Status': 'INTEGER', 'G1_Status': 'INTEGER', 'G2_Status': 'INTEGER', 'G3_Status': 'INTEGER',
        'G4_Status': 'INTEGER', 'G5_Status': 'INTEGER', 'G6_Status': 'INTEGER', 'G7_Status': 'INTEGER',
        'AnalysisType': 'INTEGER', 'BC880': 'INTEGER', 'BC_ValidData': 'float', 'BB': 'float',
        'BCff': 'float', 'BCbb': 'float', 'b': 'float', 'OC': 'float',
        'EC': 'float', 'ECff': 'float', 'ECbb': 'float', 'POC': 'float',
        'POCff': 'float', 'POCbb': 'float', 'SOC': 'float', 'TCconc_surface': 'INTEGER',
        'PunchArea': 'float', 'TCmass': 'INTEGER', 'TC_Counts': 'float', 'Zero_Counts': 'float',
        'Chamber': 'INTEGER', 'FilterIntegrity': 'INTEGER', 'SampleFlow': 'float', 'AnalyticFlow': 'float',
        'Volume': 'float', 'Pressure': 'float', 'Temp': 'float', 'SetupID': 'INTEGER',
        'SettingsID': 'INTEGER', 'CO2': 'float',
    },
    'SettingsView': {
        'ID': 'INTEGER', 'TimestampLocal': '', 'SerialNumber': 'TEXT', 'Language': 'TEXT',
        'DHCP': 'INTEGER', 'InstrumentIP': 'TEXT', 'SubnetMask': 'TEXT', 'Gateway': 'TEXT',
        'DNS': 'TEXT', 'HomeChartPeriod': 'INTEGER', 'HomeChartData': 'INTEGER', 'Display': 'INTEGER',
        'RasEnabled': 'INTEGER', 'AdpEnabled': 'INTEGER', 'AeroBaudRate': 'INTEGER', 'AeroDelimiter': 'INTEGER',
        'UidepEnabled': 'INTEGER', 'BHparamID': 'INTEGER', 'BHBaudRate': 'INTEGER', 'ModBusID': 'INTEGER',
        'ModBusBaudRate': 'INTEGER', 'ModBusEnabled': 'INTEGER',
    },
    'SetupView': {
        'ID': 'INTEGER', 'TimestampLocal': '', 'SerialNumber': 'TEXT', 'NDIRSerialNumber': 'varchar',
        'FirmwareVersion': 'TEXT', 'SoftwareVersion': 'TEXT', 'SystemVersion': 'TEXT', 'Timebase': 'INTEGER',
        'Area': 'REAL', 'SetFlowS': 'REAL', 'SetFlowA': 'REAL', 'FlowSa0': 'REAL',
        'FlowSa1': 'REAL', 'FlowSa2': 'REAL', 'FlowAa0': 'REAL', 'FlowAa1': 'REAL',
        'FlowAa2': 'REAL', 'CCch1': 'REAL', 'CCch2': 'REAL', 'SlopeTempCh1': 'REAL',
        'InterceptTempCh1': 'REAL', 'SlopeTempCh2': 'REAL', 'InterceptTempCh2': 'REAL', 'C0': 'INTEGER',
        'C1': 'INTEGER', 'C2': 'INTEGER', 'C3': 'INTEGER', 'C4': 'INTEGER',
        'C5': 'INTEGER', 'C6': 'INTEGER', 'P11': 'INTEGER', 'P12': 'INTEGER',
        'P13': 'INTEGER', 'P21': 'INTEGER', 'P22': 'INTEGER', 'P23': 'INTEGER',
        'PS1a0': 'REAL', 'PS1a1': 'REAL', 'PS1a2': 'REAL', 'PS1a3': 'REAL',
        'PS2a0': 'REAL', 'PS2a1': 'REAL', 'PS2a2': 'REAL', 'PS2a3': 'REAL',
        'A0': 'INTEGER', 'A2': 'INTEGER', 'A3': 'INTEGER', 'FlowRepStd': 'INTEGER',
        'Pressure': 'REAL', 'Temp': 'REAL', 'OC_BC_PrimaryRatio_ff': 'float', 'OC_BC_PrimaryRatio_bb': 'float',
        'CleanAirTestEnabled': 'INTEGER', 'CleanAirTestType': 'INTEGER', 'CleanAirTestDay': 'INTEGER', 'CleanAirTestTime': '',
        'CleanAirLimit': 'INTEGER', 'CleanChambers': 'INTEGER', 'HeaterSavingMode': 'INTEGER', 'HeaterSavingModeCount': 'INTEGER',
        'LeakageTest': 'INTEGER', 'b': 'REAL', 'DST': 'INTEGER', 'TimeZone': 'TEXT',
        'TimeSync': 'INTEGER', 'FilterIntegrityThreshold': 'REAL', 'NTPserver': 'TEXT',
    },
    'TestReportsView': {
        'ID': 'INTEGER', 'TimestampLocal': '', 'Type': 'SMALLINT', 'Passed': 'TINYINT',
        'Report': 'NVARCHAR (4000)',
    },
}

